all:
	mkdir -p code
	cd code && opengeode --toAda /home/taste/workspace/SpaceCreator/spacecreator/tests/integrationtests/applications/tmc/use-cases/resources/uart_protocol_dlc/work/bcdlct/SDL/src/system_structure.pr 
	asn1scc -fp AUTO -typePrefix asn1Scc -o code -equal -Ada dataview-uniq.asn code/bcdlct_datamodel.asn
	cd code && gnat make bcdlct
clean:
	rm -rf code