
/* Header file for function MMI in GUI language
 * Generated by TASTE on 2022-04-23 23:18:04
 * Context Parameters present : NO
 * Provided interfaces : Poll, action
 * Required interfaces : trigger
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void mmi_startup(void);

/* Provided interfaces */
void mmi_PI_Poll( void );


void mmi_PI_action( const asn1SccT_Int32 * );

/* Required interfaces */
extern void mmi_RI_trigger( const asn1SccT_Int32 * );


#ifdef __cplusplus
}
#endif

