/* Body file for function CImplSeqOfVariableSize
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "cimplseqofvariablesize.h"
#include <string.h>

void cimplseqofvariablesize_startup(void)
{

}

void cimplseqofvariablesize_PI_ri_seqOfVariableSizeIface
      (const asn1SccSeqOfVarSizeBoolAlias *IN_i1,
       const asn1SccSeqOfSeqOfVarSizeBoolAlias *IN_i2,
       const asn1SccSeqOfSeqOfSeqOfVarSizeBoolAlias *IN_i3,
       const asn1SccSeqOfVarSizeIntegerAlias *IN_i4,
       const asn1SccSeqOfSeqOfVarSizeIntegerAlias *IN_i5,
       const asn1SccSeqOfSeqOfSeqOfVarSizeIntegerAlias *IN_i6,
       const asn1SccSeqOfVarSizeRealAlias *IN_i7,
       const asn1SccSeqOfSeqOfVarSizeRealAlias *IN_i8,
       const asn1SccSeqOfSeqOfSeqOfVarSizeRealAlias *IN_i9,
       const asn1SccSeqOfVarSizeIA5StringFixedSizeAlias *IN_i10,
       const asn1SccSeqOfSeqOfVarSizeIA5StringFixedSizeAlias *IN_i11,
       const asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAlias *IN_i12,
       const asn1SccSeqOfVarSizeIA5StringVarSizeAlias *IN_i13,
       const asn1SccSeqOfSeqOfVarSizeIA5StringVarSizeAlias *IN_i14,
       const asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringVarSizeAlias *IN_i15,
       const asn1SccSeqOfVarSizeOctetStringFixedSizeAlias *IN_i16,
       const asn1SccSeqOfSeqOfVarSizeOctetStringFixedSizeAlias *IN_i17,
       const asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAlias *IN_i18,
       const asn1SccSeqOfVarSizeOctetStringVarSizeAlias *IN_i19,
       const asn1SccSeqOfSeqOfVarSizeOctetStringVarSizeAlias *IN_i20,
       const asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringVarSizeAlias *IN_i21,
       const asn1SccSeqOfVarSizeEnumAlias *IN_i22,
       const asn1SccSeqOfSeqOfVarSizeEnumAlias *IN_i23,
       const asn1SccSeqOfSeqOfSeqOfVarSizeEnumAlias *IN_i24,
       const asn1SccSeqOfVarSizeSeqAliases *IN_i25,
       const asn1SccSeqOfSeqOfVarSizeSeqAliases *IN_i26,
       const asn1SccSeqOfSeqOfSeqOfVarSizeSeqAliases *IN_i27,
       const asn1SccSeqOfVarSizeSeqBuiltIn *IN_i28,
       const asn1SccSeqOfSeqOfVarSizeSeqBuiltIn *IN_i29,
       const asn1SccSeqOfSeqOfSeqOfVarSizeSeqBuiltIn *IN_i30,

       asn1SccSeqOfVarSizeBoolAlias *OUT_o1,
       asn1SccSeqOfSeqOfVarSizeBoolAlias *OUT_o2,
       asn1SccSeqOfSeqOfSeqOfVarSizeBoolAlias *OUT_o3,
       asn1SccSeqOfVarSizeIntegerAlias *OUT_o4,
       asn1SccSeqOfSeqOfVarSizeIntegerAlias *OUT_o5,
       asn1SccSeqOfSeqOfSeqOfVarSizeIntegerAlias *OUT_o6,
       asn1SccSeqOfVarSizeRealAlias *OUT_o7,
       asn1SccSeqOfSeqOfVarSizeRealAlias *OUT_o8,
       asn1SccSeqOfSeqOfSeqOfVarSizeRealAlias *OUT_o9,
       asn1SccSeqOfVarSizeIA5StringFixedSizeAlias *OUT_o10,
       asn1SccSeqOfSeqOfVarSizeIA5StringFixedSizeAlias *OUT_o11,
       asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAlias *OUT_o12,
       asn1SccSeqOfVarSizeIA5StringVarSizeAlias *OUT_o13,
       asn1SccSeqOfSeqOfVarSizeIA5StringVarSizeAlias *OUT_o14,
       asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringVarSizeAlias *OUT_o15,
       asn1SccSeqOfVarSizeOctetStringFixedSizeAlias *OUT_o16,
       asn1SccSeqOfSeqOfVarSizeOctetStringFixedSizeAlias *OUT_o17,
       asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAlias *OUT_o18,
       asn1SccSeqOfVarSizeOctetStringVarSizeAlias *OUT_o19,
       asn1SccSeqOfSeqOfVarSizeOctetStringVarSizeAlias *OUT_o20,
       asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringVarSizeAlias *OUT_o21,
       asn1SccSeqOfVarSizeEnumAlias *OUT_o22,
       asn1SccSeqOfSeqOfVarSizeEnumAlias *OUT_o23,
       asn1SccSeqOfSeqOfSeqOfVarSizeEnumAlias *OUT_o24,
       asn1SccSeqOfVarSizeSeqAliases *OUT_o25,
       asn1SccSeqOfSeqOfVarSizeSeqAliases *OUT_o26,
       asn1SccSeqOfSeqOfSeqOfVarSizeSeqAliases *OUT_o27,
       asn1SccSeqOfVarSizeSeqBuiltIn *OUT_o28,
       asn1SccSeqOfSeqOfVarSizeSeqBuiltIn *OUT_o29,
       asn1SccSeqOfSeqOfSeqOfVarSizeSeqBuiltIn *OUT_o30)

{
    memcpy(OUT_o1, IN_i1, sizeof(asn1SccSeqOfVarSizeBoolAlias));
    memcpy(OUT_o2, IN_i2, sizeof(asn1SccSeqOfSeqOfVarSizeBoolAlias));
    memcpy(OUT_o3, IN_i3, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeBoolAlias));
    memcpy(OUT_o4, IN_i4, sizeof(asn1SccSeqOfVarSizeIntegerAlias));
    memcpy(OUT_o5, IN_i5, sizeof(asn1SccSeqOfSeqOfVarSizeIntegerAlias));
    memcpy(OUT_o6, IN_i6, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeIntegerAlias));
    memcpy(OUT_o7, IN_i7, sizeof(asn1SccSeqOfVarSizeRealAlias));
    memcpy(OUT_o8, IN_i8, sizeof(asn1SccSeqOfSeqOfVarSizeRealAlias));
    memcpy(OUT_o9, IN_i9, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeRealAlias));
    memcpy(OUT_o10, IN_i10, sizeof(asn1SccSeqOfVarSizeIA5StringFixedSizeAlias));
    memcpy(OUT_o11, IN_i11, sizeof(asn1SccSeqOfSeqOfVarSizeIA5StringFixedSizeAlias));
    memcpy(OUT_o12, IN_i12, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAlias));
    memcpy(OUT_o13, IN_i13, sizeof(asn1SccSeqOfVarSizeIA5StringVarSizeAlias));
    memcpy(OUT_o14, IN_i14, sizeof(asn1SccSeqOfSeqOfVarSizeIA5StringVarSizeAlias));
    memcpy(OUT_o15, IN_i15, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringVarSizeAlias));
    memcpy(OUT_o16, IN_i16, sizeof(asn1SccSeqOfVarSizeOctetStringFixedSizeAlias));
    memcpy(OUT_o17, IN_i17, sizeof(asn1SccSeqOfSeqOfVarSizeOctetStringFixedSizeAlias));
    memcpy(OUT_o18, IN_i18, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAlias));
    memcpy(OUT_o19, IN_i19, sizeof(asn1SccSeqOfVarSizeOctetStringVarSizeAlias));
    memcpy(OUT_o20, IN_i20, sizeof(asn1SccSeqOfSeqOfVarSizeOctetStringVarSizeAlias));
    memcpy(OUT_o21, IN_i21, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringVarSizeAlias));
    memcpy(OUT_o22, IN_i22, sizeof(asn1SccSeqOfVarSizeEnumAlias));
    memcpy(OUT_o23, IN_i23, sizeof(asn1SccSeqOfSeqOfVarSizeEnumAlias));
    memcpy(OUT_o24, IN_i24, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeEnumAlias));
    memcpy(OUT_o25, IN_i25, sizeof(asn1SccSeqOfVarSizeSeqAliases));
    memcpy(OUT_o26, IN_i26, sizeof(asn1SccSeqOfSeqOfVarSizeSeqAliases));
    memcpy(OUT_o27, IN_i27, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeSeqAliases));
    memcpy(OUT_o28, IN_i28, sizeof(asn1SccSeqOfVarSizeSeqBuiltIn));
    memcpy(OUT_o29, IN_i29, sizeof(asn1SccSeqOfSeqOfVarSizeSeqBuiltIn));
    memcpy(OUT_o30, IN_i30, sizeof(asn1SccSeqOfSeqOfSeqOfVarSizeSeqBuiltIn));
}
