/* Body file for function Controller
 * Generated by TASTE on 2022-08-18 12:02:38
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Trigger
 * Required interfaces : Iface
 * User-defined properties for this function:
 * Timers              : 
 */

#include "controller.h"
#include <stdio.h>
#include <assert.h>


void controller_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Controller] Startup");
}

void controller_PI_Trigger(void)
{
   asn1SccMySeqSimple inputParamInner;
   inputParamInner.intSeqElement = 2;
   inputParamInner.realSeqElement = 4.0;
   inputParamInner.boolSeqElement = false;

   asn1SccMySeqSimple outputParamInner;
   outputParamInner.intSeqElement = 0;
   outputParamInner.realSeqElement = 0.0;
   outputParamInner.boolSeqElement = false;

   asn1SccMySeqSimple expectedOutputInner;
   expectedOutputInner.intSeqElement = 4;
   expectedOutputInner.realSeqElement = 8.0;
   expectedOutputInner.boolSeqElement = true;

   asn1SccMySeqComplex inputParam;
   asn1SccMySeqComplex outputParam;
   asn1SccMySeqComplex expectedOutput;

   inputParam.simpleSeq1 = inputParamInner;
   inputParam.simpleSeq2 = inputParamInner;
   outputParam.simpleSeq1 = outputParamInner;
   outputParam.simpleSeq2 = outputParamInner;
   expectedOutput.simpleSeq1 = expectedOutputInner;
   expectedOutput.simpleSeq2 = expectedOutputInner;

   controller_RI_Iface( &inputParam, &outputParam );
   printf("Output (seq 1): %u %f %d\n", outputParam.simpleSeq1.intSeqElement,
         outputParam.simpleSeq1.realSeqElement, outputParam.simpleSeq1.boolSeqElement);
   printf("Output (seq 2): %u %f %d\n", outputParam.simpleSeq2.intSeqElement,
      outputParam.simpleSeq2.realSeqElement, outputParam.simpleSeq2.boolSeqElement);

   assert(outputParam.simpleSeq1.intSeqElement == expectedOutput.simpleSeq1.intSeqElement);
   assert(abs(outputParam.simpleSeq1.realSeqElement - expectedOutput.simpleSeq1.realSeqElement) < 0.001f);
   assert(outputParam.simpleSeq1.boolSeqElement == expectedOutput.simpleSeq1.boolSeqElement);

   assert(outputParam.simpleSeq2.intSeqElement == expectedOutput.simpleSeq2.intSeqElement);
   assert(abs(outputParam.simpleSeq2.realSeqElement - expectedOutput.simpleSeq2.realSeqElement) < 0.001f);
   assert(outputParam.simpleSeq2.boolSeqElement == expectedOutput.simpleSeq2.boolSeqElement);
}


