-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by TASTE (kazoo/templates/glue/language_wrappers/ri_adb/function.tmplt)
package body Actuator2_RI is

   procedure Actuatortm
      (Tm : in out asn1SccActuatorstatus;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Actuatortm
         (Dest_PID : asn1sccPID;
          Tm : in out asn1SccActuatorstatus)
         with Import,
              Convention => C,
              Link_Name  => "actuator2_RI_actuatorTm_To_PID";
   begin
         C_Actuatortm (Dest_PID, tm);
   end Actuatortm;

end Actuator2_RI;
