-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by TASTE (kazoo/templates/glue/language_wrappers/ri_adb/function.tmplt)
package body Modemanager_RI is

   procedure Actuatortc1
      (Tc : in out asn1SccActuatorcommand;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Actuatortc1
         (Dest_PID : asn1sccPID;
          Tc : in out asn1SccActuatorcommand)
         with Import,
              Convention => C,
              Link_Name  => "modemanager_RI_actuatorTc1_To_PID";
   begin
         C_Actuatortc1 (Dest_PID, tc);
   end Actuatortc1;
   
   
   
   procedure Actuatortc2
      (Tc : in out asn1SccActuatorcommand;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Actuatortc2
         (Dest_PID : asn1sccPID;
          Tc : in out asn1SccActuatorcommand)
         with Import,
              Convention => C,
              Link_Name  => "modemanager_RI_actuatorTc2_To_PID";
   begin
         C_Actuatortc2 (Dest_PID, tc);
   end Actuatortc2;
   
   
   
   procedure Systemtm
      (Tm : in out asn1SccSystemtelemetry;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Systemtm
         (Dest_PID : asn1sccPID;
          Tm : in out asn1SccSystemtelemetry)
         with Import,
              Convention => C,
              Link_Name  => "modemanager_RI_systemTm_To_PID";
   begin
         C_Systemtm (Dest_PID, tm);
   end Systemtm;

end Modemanager_RI;
