Lockb-Datamodel DEFINITIONS ::=
BEGIN
IMPORTS
   T-UInt16, T-WriteAccess, T-ByteArray, T-MemBuffer, T-WriteRequest, T-ProcID FROM DEKKER1-DATAVIEW
   T-Int32, T-UInt32, T-Int8, T-UInt8, T-Boolean, T-Null-Record FROM TASTE-BasicTypes;

Lockb-States ::= ENUMERATED {lockb-has-no-state}

Lockb-Context ::= SEQUENCE {
init-done BOOLEAN
}

END
