/* Header file for function Controller
 * Generated by TASTE on 2022-08-10 13:58:31
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void controller_startup(void);

/* Provided interfaces */
void controller_PI_Trigger( void );

/* Required interfaces */
extern void controller_RI_Iface( const asn1SccMySeq *, const asn1SccMySeq * );


#ifdef __cplusplus
}
#endif
