/* Body file for function ControlSystem
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "controlsystem_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void controlsystem_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned controlsystem_initialized = 0;
void init_controlsystem(void)
{
   if (0 == controlsystem_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      controlsystem_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      puts ("[TASTE] Initialization completed for function ControlSystem");
      controlsystem_initialized = 2;
   }
}
void controlsystem_configuration
      (const char *IN_cfg, size_t IN_cfg_len)

{
   sender_pid = controlsystem_configuration_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: controlsystem,configuration,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void controlsystem_PI_configuration
      (const asn1SccPidConfig *);





   // Call user code
   controlsystem_PI_configuration ((asn1SccPidConfig *)IN_cfg);

   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *controlsystem_state(void);
      printf ("INNER_SDL_STATE: controlsystem,%s\n", controlsystem_state());
      fflush(stdout);
   }
}




void controlsystem_reading
      (const char *IN_signalvalue, size_t IN_signalvalue_len)

{
   sender_pid = controlsystem_reading_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: controlsystem,reading,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void controlsystem_PI_reading
      (const asn1SccNumber *);





   // Call user code
   controlsystem_PI_reading ((asn1SccNumber *)IN_signalvalue);

   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *controlsystem_state(void);
      printf ("INNER_SDL_STATE: controlsystem,%s\n", controlsystem_state());
      fflush(stdout);
   }
}

