SET(IV_DIR ../../../../../TASTEeditor)

SET(IV_SOURCES
    ${IV_DIR}/app/commandlineparser.h
    ${IV_DIR}/app/commandsstack.h
    ${IV_DIR}/app/common.h
    ${IV_DIR}/app/context/action/action.h
    ${IV_DIR}/app/context/action/actionsmanager.h
    ${IV_DIR}/app/context/action/attrhandler.h
    ${IV_DIR}/app/context/action/condition.h
    ${IV_DIR}/app/context/action/editor/actionsmodel.h
    ${IV_DIR}/app/context/action/editor/attributesmodel.h
    ${IV_DIR}/app/context/action/editor/conditiondialog.h
    ${IV_DIR}/app/context/action/editor/conditionsmodel.h
    ${IV_DIR}/app/context/action/editor/dynactioneditor.h
    ${IV_DIR}/app/context/action/extprocmonitor.h
    ${IV_DIR}/app/datatypes/basicdatatype.h
    ${IV_DIR}/app/datatypes/datatypesstorage.h
#    ${IV_DIR}/app/mainwindow.h
    ${IV_DIR}/app/xmldocexporter.h
    ${IV_DIR}/app/zoomcontroller.h
    ${IV_DIR}/baseitems/common/abstractinteractiveobject.h
    ${IV_DIR}/baseitems/common/drawrectinfo.h
    ${IV_DIR}/baseitems/common/highlightrectitem.h
    ${IV_DIR}/baseitems/common/utils.h
    ${IV_DIR}/baseitems/graphicsview.h
    ${IV_DIR}/baseitems/grippoint.h
    ${IV_DIR}/baseitems/grippointshandler.h
    ${IV_DIR}/baseitems/interactiveobject.h
    ${IV_DIR}/baseitems/textgraphicsitem.h
    ${IV_DIR}/document/abstracttabdocument.h
    ${IV_DIR}/document/documentsmanager.h
    ${IV_DIR}/document/tabdocumentfactory.h
    ${IV_DIR}/dummy/dummytabdocument.h
#    ${IV_DIR}/logging/logcategory.h
#    ${IV_DIR}/logging/loghandler.h
    ${IV_DIR}/templating/stringtemplate.h
    ${IV_DIR}/templating/abstractexportableobject.h
    ${IV_DIR}/templating/exportableaadlconnection.h
    ${IV_DIR}/templating/exportableaadlfunction.h
    ${IV_DIR}/templating/exportableaadliface.h
    ${IV_DIR}/templating/exportableaadlobject.h
    ${IV_DIR}/templating/exportableproperty.h
    ${IV_DIR}/templating/templateeditor.h
    ${IV_DIR}/templating/templatehighlighter.h
    ${IV_DIR}/templating/xmlhighlighter.h
    ${IV_DIR}/templating/templatesyntaxhelpdialog.h
#    ${IV_DIR}/reports/bugreportdialog.h
#    ${IV_DIR}/reports/bugreporthandler.h
    ${IV_DIR}/settings/appoptions.h
    ${IV_DIR}/settings/settingsmanager.h
    ${IV_DIR}/tab_aadl/aadlcommonprops.h
    ${IV_DIR}/tab_aadl/aadlnamevalidator.h
    ${IV_DIR}/tab_aadl/aadlobject.h
    ${IV_DIR}/tab_aadl/aadlobjectcomment.h
    ${IV_DIR}/tab_aadl/aadlobjectconnection.h
    ${IV_DIR}/tab_aadl/aadlobjectfunction.h
    ${IV_DIR}/tab_aadl/aadlobjectfunctiontype.h
    ${IV_DIR}/tab_aadl/aadlobjectiface.h
    ${IV_DIR}/tab_aadl/aadlobjectsmodel.h
    ${IV_DIR}/tab_aadl/aadlparameter.h
    ${IV_DIR}/tab_aadl/aadltabdocument.h
    ${IV_DIR}/tab_aadl/aadlxmlreader.h
    ${IV_DIR}/tab_concurrency/concurrencytabdocument.h
    ${IV_DIR}/tab_data/datatabdocument.h
    ${IV_DIR}/tab_deployment/deploymenttabdocument.h
    ${IV_DIR}/tab_interface/aadlcommentgraphicsitem.h
    ${IV_DIR}/tab_interface/aadlconnectiongraphicsitem.h
    ${IV_DIR}/tab_interface/aadlfunctiongraphicsitem.h
    ${IV_DIR}/tab_interface/aadlfunctionnamegraphicsitem.h
    ${IV_DIR}/tab_interface/aadlfunctiontypegraphicsitem.h
    ${IV_DIR}/tab_interface/aadlinterfacegraphicsitem.h
    ${IV_DIR}/tab_interface/aadlrectgraphicsitem.h
    ${IV_DIR}/tab_interface/commenttextdialog.h
    ${IV_DIR}/tab_interface/colors/colorhandlereditor.h
    ${IV_DIR}/tab_interface/colors/colormanager.h
    ${IV_DIR}/tab_interface/colors/colormanagerdialog.h
    ${IV_DIR}/tab_interface/colors/colorselectorbutton.h
    ${IV_DIR}/tab_interface/commands/cmdcommentitemcreate.h
    ${IV_DIR}/tab_interface/commands/cmdconnectionitemcreate.h
    ${IV_DIR}/tab_interface/commands/cmdcontextparameterchange.h
    ${IV_DIR}/tab_interface/commands/cmdcontextparametercreate.h
    ${IV_DIR}/tab_interface/commands/cmdcontextparameterremove.h
    ${IV_DIR}/tab_interface/commands/cmdentityautolayout.h
    ${IV_DIR}/tab_interface/commands/cmdentityattributechange.h
    ${IV_DIR}/tab_interface/commands/cmdentitygeometrychange.h
    ${IV_DIR}/tab_interface/commands/cmdentitypropertychange.h
    ${IV_DIR}/tab_interface/commands/cmdentitypropertycreate.h
    ${IV_DIR}/tab_interface/commands/cmdentitypropertyremove.h
    ${IV_DIR}/tab_interface/commands/cmdentitypropertyrename.h
    ${IV_DIR}/tab_interface/commands/cmdentityremove.h
    ${IV_DIR}/tab_interface/commands/cmdfunctionitemcreate.h
    ${IV_DIR}/tab_interface/commands/cmdfunctiontypeitemcreate.h
    ${IV_DIR}/tab_interface/commands/cmdifacedatachangebase.h
    ${IV_DIR}/tab_interface/commands/cmdifaceparambase.h
    ${IV_DIR}/tab_interface/commands/cmdifaceparamcreate.h
    ${IV_DIR}/tab_interface/commands/cmdifaceparamremove.h
    ${IV_DIR}/tab_interface/commands/cmdifaceparamchange.h
    ${IV_DIR}/tab_interface/commands/cmdifaceattrchange.h
    ${IV_DIR}/tab_interface/commands/cmdinterfaceitemcreate.h
    ${IV_DIR}/tab_interface/commands/cmdrequiredifacepropertychange.h
    ${IV_DIR}/tab_interface/commands/cmdrootentitychange.h
    ${IV_DIR}/tab_interface/commands/commandids.h
    ${IV_DIR}/tab_interface/commands/commandsfactory.h
    ${IV_DIR}/tab_interface/connectioncreationvalidator.h
    ${IV_DIR}/tab_interface/creatortool.h
    ${IV_DIR}/tab_interface/graphicsitemhelpers.h
    ${IV_DIR}/tab_interface/interfacetabdocument.h
    ${IV_DIR}/tab_interface/interfacetabgraphicsscene.h
    ${IV_DIR}/tab_interface/properties/adddynamicpropertydialog.h
    ${IV_DIR}/tab_interface/properties/contextparametersmodel.h
    ${IV_DIR}/tab_interface/properties/delegates/comboboxdelegate.h
    ${IV_DIR}/tab_interface/properties/delegates/functionattrdelegate.h
    ${IV_DIR}/tab_interface/properties/delegates/interfaceattrdelegate.h
    ${IV_DIR}/tab_interface/properties/delegates/propertytypedelegate.h
    ${IV_DIR}/tab_interface/properties/dynamicproperty.h
    ${IV_DIR}/tab_interface/properties/dynamicpropertyconfig.h
    ${IV_DIR}/tab_interface/properties/dynamicpropertymanager.h
    ${IV_DIR}/tab_interface/properties/ifaceparametersmodel.h
    ${IV_DIR}/tab_interface/properties/propertiesdialog.h
    ${IV_DIR}/tab_interface/properties/propertieslistmodel.h
    ${IV_DIR}/tab_interface/properties/propertiesmodelbase.h
    ${IV_DIR}/tab_interface/properties/propertiesviewbase.h
    ${IV_DIR}/tab_msc/msctabdocument.h
    ${IV_DIR}/util/delayedsignal.h
    ${IV_DIR}/app/commandlineparser.cpp
    ${IV_DIR}/app/commandsstack.cpp
    ${IV_DIR}/app/common.cpp
    ${IV_DIR}/app/context/action/action.cpp
    ${IV_DIR}/app/context/action/actionsmanager.cpp
    ${IV_DIR}/app/context/action/attrhandler.cpp
    ${IV_DIR}/app/context/action/condition.cpp
    ${IV_DIR}/app/context/action/editor/actionsmodel.cpp
    ${IV_DIR}/app/context/action/editor/attributesmodel.cpp
    ${IV_DIR}/app/context/action/editor/conditiondialog.cpp
    ${IV_DIR}/app/context/action/editor/conditionsmodel.cpp
    ${IV_DIR}/app/context/action/editor/dynactioneditor.cpp
    ${IV_DIR}/app/context/action/extprocmonitor.cpp
    ${IV_DIR}/app/datatypes/basicdatatype.cpp
    ${IV_DIR}/app/datatypes/datatypesstorage.cpp
#    ${IV_DIR}/app/mainwindow.cpp
    ${IV_DIR}/app/xmldocexporter.cpp
    ${IV_DIR}/app/zoomcontroller.cpp
    ${IV_DIR}/baseitems/common/drawrectinfo.cpp
    ${IV_DIR}/baseitems/common/highlightrectitem.cpp
    ${IV_DIR}/baseitems/common/utils.cpp
    ${IV_DIR}/baseitems/graphicsview.cpp
    ${IV_DIR}/baseitems/grippoint.cpp
    ${IV_DIR}/baseitems/grippointshandler.cpp
    ${IV_DIR}/baseitems/interactiveobject.cpp
    ${IV_DIR}/baseitems/textgraphicsitem.cpp
    ${IV_DIR}/document/abstracttabdocument.cpp
    ${IV_DIR}/document/documentsmanager.cpp
    ${IV_DIR}/document/tabdocumentfactory.cpp
    ${IV_DIR}/dummy/dummytabdocument.cpp
#    ${IV_DIR}/logging/logcategory.cpp
#    ${IV_DIR}/logging/loghandler.cpp
    ${IV_DIR}/templating/stringtemplate.cpp
    ${IV_DIR}/templating/exportableaadlconnection.cpp
    ${IV_DIR}/templating/exportableaadlfunction.cpp
    ${IV_DIR}/templating/exportableaadliface.cpp
    ${IV_DIR}/templating/exportableaadlobject.cpp
    ${IV_DIR}/templating/templateeditor.cpp
    ${IV_DIR}/templating/templatehighlighter.cpp
    ${IV_DIR}/templating/xmlhighlighter.cpp
    ${IV_DIR}/templating/templatesyntaxhelpdialog.cpp
#    ${IV_DIR}/reports/bugreportdialog.cpp
#    ${IV_DIR}/reports/bugreporthandler.cpp
    ${IV_DIR}/settings/appoptions.cpp
    ${IV_DIR}/settings/settingsmanager.cpp
    ${IV_DIR}/tab_aadl/aadlcommonprops.cpp
    ${IV_DIR}/tab_aadl/aadlnamevalidator.cpp
    ${IV_DIR}/tab_aadl/aadlobject.cpp
    ${IV_DIR}/tab_aadl/aadlobjectcomment.cpp
    ${IV_DIR}/tab_aadl/aadlobjectconnection.cpp
    ${IV_DIR}/tab_aadl/aadlobjectfunction.cpp
    ${IV_DIR}/tab_aadl/aadlobjectfunctiontype.cpp
    ${IV_DIR}/tab_aadl/aadlobjectiface.cpp
    ${IV_DIR}/tab_aadl/aadlobjectsmodel.cpp
    ${IV_DIR}/tab_aadl/aadlparameter.cpp
    ${IV_DIR}/tab_aadl/aadltabdocument.cpp
    ${IV_DIR}/tab_aadl/aadlxmlreader.cpp
    ${IV_DIR}/tab_concurrency/concurrencytabdocument.cpp
    ${IV_DIR}/tab_data/datatabdocument.cpp
    ${IV_DIR}/tab_deployment/deploymenttabdocument.cpp
    ${IV_DIR}/tab_interface/aadlcommentgraphicsitem.cpp
    ${IV_DIR}/tab_interface/aadlconnectiongraphicsitem.cpp
    ${IV_DIR}/tab_interface/aadlfunctiongraphicsitem.cpp
    ${IV_DIR}/tab_interface/aadlfunctionnamegraphicsitem.cpp
    ${IV_DIR}/tab_interface/aadlfunctiontypegraphicsitem.cpp
    ${IV_DIR}/tab_interface/aadlinterfacegraphicsitem.cpp
    ${IV_DIR}/tab_interface/aadlrectgraphicsitem.cpp
    ${IV_DIR}/tab_interface/commenttextdialog.cpp
    ${IV_DIR}/tab_interface/colors/colorhandlereditor.cpp
    ${IV_DIR}/tab_interface/colors/colormanager.cpp
    ${IV_DIR}/tab_interface/colors/colormanagerdialog.cpp
    ${IV_DIR}/tab_interface/colors/colorselectorbutton.cpp
    ${IV_DIR}/tab_interface/commands/cmdcommentitemcreate.cpp
    ${IV_DIR}/tab_interface/commands/cmdconnectionitemcreate.cpp
    ${IV_DIR}/tab_interface/commands/cmdcontextparameterchange.cpp
    ${IV_DIR}/tab_interface/commands/cmdcontextparametercreate.cpp
    ${IV_DIR}/tab_interface/commands/cmdcontextparameterremove.cpp
    ${IV_DIR}/tab_interface/commands/cmdentityautolayout.cpp
    ${IV_DIR}/tab_interface/commands/cmdentityattributechange.cpp
    ${IV_DIR}/tab_interface/commands/cmdentitygeometrychange.cpp
    ${IV_DIR}/tab_interface/commands/cmdentitypropertychange.cpp
    ${IV_DIR}/tab_interface/commands/cmdentitypropertycreate.cpp
    ${IV_DIR}/tab_interface/commands/cmdentitypropertyremove.cpp
    ${IV_DIR}/tab_interface/commands/cmdentitypropertyrename.cpp
    ${IV_DIR}/tab_interface/commands/cmdentityremove.cpp
    ${IV_DIR}/tab_interface/commands/cmdfunctionitemcreate.cpp
    ${IV_DIR}/tab_interface/commands/cmdfunctiontypeitemcreate.cpp
    ${IV_DIR}/tab_interface/commands/cmdifacedatachangebase.cpp
    ${IV_DIR}/tab_interface/commands/cmdifaceparambase.cpp
    ${IV_DIR}/tab_interface/commands/cmdifaceparamcreate.cpp
    ${IV_DIR}/tab_interface/commands/cmdifaceparamremove.cpp
    ${IV_DIR}/tab_interface/commands/cmdifaceparamchange.cpp
    ${IV_DIR}/tab_interface/commands/cmdifaceattrchange.cpp
    ${IV_DIR}/tab_interface/commands/cmdinterfaceitemcreate.cpp
    ${IV_DIR}/tab_interface/commands/cmdrequiredifacepropertychange.cpp
    ${IV_DIR}/tab_interface/commands/cmdrootentitychange.cpp
    ${IV_DIR}/tab_interface/commands/commandsfactory.cpp
    ${IV_DIR}/tab_interface/connectioncreationvalidator.cpp
    ${IV_DIR}/tab_interface/creatortool.cpp
    ${IV_DIR}/tab_interface/graphicsitemhelpers.cpp
    ${IV_DIR}/tab_interface/interfacetabdocument.cpp
    ${IV_DIR}/tab_interface/interfacetabgraphicsscene.cpp
    ${IV_DIR}/tab_interface/properties/adddynamicropertydialog.cpp
    ${IV_DIR}/tab_interface/properties/contextparametersmodel.cpp
    ${IV_DIR}/tab_interface/properties/delegates/comboboxdelegate.cpp
    ${IV_DIR}/tab_interface/properties/delegates/functionattrdelegate.cpp
    ${IV_DIR}/tab_interface/properties/delegates/interfaceattrdelegate.cpp
    ${IV_DIR}/tab_interface/properties/delegates/propertytypedelegate.cpp
    ${IV_DIR}/tab_interface/properties/dynamicproperty.cpp
    ${IV_DIR}/tab_interface/properties/dynamicpropertyconfig.cpp
    ${IV_DIR}/tab_interface/properties/dynamicpropertymanager.cpp
    ${IV_DIR}/tab_interface/properties/ifaceparametersmodel.cpp
    ${IV_DIR}/tab_interface/properties/propertiesdialog.cpp
    ${IV_DIR}/tab_interface/properties/propertieslistmodel.cpp
    ${IV_DIR}/tab_interface/properties/propertiesmodelbase.cpp
    ${IV_DIR}/tab_interface/properties/propertiesviewbase.cpp
    ${IV_DIR}/tab_msc/msctabdocument.cpp
    ${IV_DIR}/util/delayedsignal.cpp
    ${IV_DIR}/app/context/action/editor/conditiondialog.ui
    ${IV_DIR}/app/context/action/editor/dynactioneditor.ui
#    ${IV_DIR}/app/mainwindow.ui
#    ${IV_DIR}/reports/bugreportdialog.ui
    ${IV_DIR}/tab_interface/commenttextdialog.ui
    ${IV_DIR}/tab_interface/colors/colorhandlereditor.ui
    ${IV_DIR}/tab_interface/colors/colormanagerdialog.ui
    ${IV_DIR}/tab_interface/properties/adddynamicpropertydialog.ui
    ${IV_DIR}/tab_interface/properties/dynamicpropertymanager.ui
    ${IV_DIR}/tab_interface/properties/propertiesdialog.ui
    ${IV_DIR}/tab_interface/properties/propertiesviewbase.ui
)
