/* Body file for function Host
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "host_vm_if.h"
#include "dataview-uniq.h"  // contains definition of PID type
#include <stdio.h>
extern long long getTimeInMilliseconds(void);

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void host_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned host_initialized = 0;
void init_host(void)
{
   if (0 == host_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      host_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      puts ("[TASTE] Initialization completed for function Host");
      host_initialized = 2;
   }
}
void host_tm(void)
{
   sender_pid = host_tm_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: host,tm,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void host_PI_tm(void);
   host_PI_tm();
   // puts ("host_tm called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *host_state(void);
      printf ("INNER_SDL_STATE: host,%s\n", host_state());
      fflush(stdout);
   }
}

