-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by TASTE (kazoo/templates/glue/language_wrappers/ri_adb/function.tmplt)
package body Host_RI is

   procedure Configuration
      (Cfg : in out asn1SccPidconfig;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Configuration
         (Dest_PID : asn1sccPID;
          Cfg : in out asn1SccPidconfig)
         with Import,
              Convention => C,
              Link_Name  => "host_RI_configuration_To_PID";
   begin
         C_Configuration (Dest_PID, cfg);
   end Configuration;
   
   
   
   procedure Tc (Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Tc
         (Dest_PID : asn1sccPID)
         with Import,
              Convention => C,
              Link_Name  => "host_RI_tc_To_PID";
   begin
         C_Tc (Dest_PID);
   end Tc;

end Host_RI;
