/*
  Copyright (C) 2019 European Space Agency - <maxime.perrotin@esa.int>

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Library General Public
  License as published by the Free Software Foundation; either
  version 2 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Library General Public License for more details.

  You should have received a copy of the GNU Library General Public License
  along with this program. If not, see <https://www.gnu.org/licenses/lgpl-2.1.html>.
*/

#include "aadlobjectiface.h"

#include "aadlcommonprops.h"
#include "aadlnamevalidator.h"
#include "aadlobjectconnection.h"
#include "aadlobjectfunction.h"
#include "aadlobjectsmodel.h"

#include <QDebug>
#include <QMetaEnum>

namespace ivm {

AADLObjectIface::CreationInfo::CreationInfo(AADLObjectsModel *model, AADLObjectFunctionType *function,
        const QPointF &position, AADLObjectIface::IfaceType type, const shared::Id &id,
        const QVector<IfaceParameter> &parameters, OperationKind kind, const QString &name,
        const CreationInfo::Policy policy, AADLObjectIface *source)
    : model(model)
    , function(function)
    , position(position)
    , type(type)
    , id(id)
    , parameters(parameters)
    , kind(kind)
    , name(name)
    , policy(policy)
    , toBeCloned(policy == Policy::Clone ? source : nullptr)
{
}

QVariantList AADLObjectIface::CreationInfo::toVarList() const
{
    return { QVariant::fromValue(*this) };
}

AADLObjectIface::CreationInfo AADLObjectIface::CreationInfo::initFromIface(
        AADLObjectIface *iface, const CreationInfo::Policy policy)
{
    if (!iface)
        return {};

    auto getIfacePos = [](const QVector<qint32> &coordinates) {
        return coordinates.size() < 2 ? QPointF() : QPointF(coordinates.front(), coordinates.back());
    };

    return { iface->objectsModel(),
        (iface->parentObject() ? iface->parentObject()->as<AADLObjectFunctionType *>() : nullptr),
        getIfacePos(iface->coordinates()), iface->direction(), iface->id(), iface->params(), iface->kind(),
        iface->title(), policy, iface };
}

AADLObjectIface::CreationInfo AADLObjectIface::CreationInfo::fromIface(AADLObjectIface *iface)
{
    AADLObjectIface::CreationInfo info = initFromIface(iface, AADLObjectIface::CreationInfo::Policy::Init);
    if (AADLNameValidator::isAutogeneratedName(iface))
        info.name = QString();
    return info;
}

AADLObjectIface::CreationInfo AADLObjectIface::CreationInfo::cloneIface(AADLObjectIface *iface, AADLObjectFunction *fn)
{
    AADLObjectIface::CreationInfo info = initFromIface(iface, AADLObjectIface::CreationInfo::Policy::Clone);
    info.function = fn;
    info.model = fn->objectsModel();
    return info;
}

void AADLObjectIface::CreationInfo::resetKind()
{
    if (AADLObjectIface::IfaceType::Required == type)
        kind = AADLObjectIface::OperationKind::Any;
    else {
        if (AADLObjectIface::OperationKind::Any == kind)
            kind = AADLObjectIface::OperationKind::Sporadic;
    }
}

struct AADLObjectIfacePrivate {
    explicit AADLObjectIfacePrivate(AADLObjectIface::IfaceType dir)
        : m_direction(dir)
    {
    }
    AADLObjectIface::IfaceType m_direction;
    QVector<IfaceParameter> m_params = {};
    QPointer<AADLObjectIface> m_cloneOf { nullptr };
    QVector<QPointer<AADLObjectIface>> m_clones {};
};

AADLObjectIface::AADLObjectIface(AADLObject::Type ifaceType, const CreationInfo &ci)
    : AADLObject(ifaceType, ci.name, ci.function, ci.toBeCloned ? shared::createId() : ci.id)
    , d(new AADLObjectIfacePrivate(Type::InterfaceGroup == ifaceType
                      ? ci.type
                      : Type::RequiredInterface == ifaceType ? AADLObjectIface::IfaceType::Required
                                                             : AADLObjectIface::IfaceType::Provided))
{
    setupInitialAttrs();

    setKind(ci.kind);
    setParams(ci.parameters);

    if (ci.toBeCloned)
        setCloneOrigin(ci.toBeCloned);
}

AADLObjectIface::~AADLObjectIface()
{
    if (d->m_cloneOf)
        d->m_cloneOf->forgetClone(this);
}

void AADLObjectIface::setupInitialAttrs()
{
    setAttr(meta::Props::token(meta::Props::Token::kind), kindToString(defaultKind()));
    if (isProvided()) {
        setAttr(meta::Props::token(meta::Props::Token::period), QVariant());
        setAttr(meta::Props::token(meta::Props::Token::wcet), QVariant());
        setAttr(meta::Props::token(meta::Props::Token::queue_size), QVariant());
    } else {
        setProp(meta::Props::token(meta::Props::Token::InheritPI), true);
    }
}

AADLObjectIface::IfaceType AADLObjectIface::direction() const
{
    return d->m_direction;
}

bool AADLObjectIface::isProvided() const
{
    return direction() == IfaceType::Provided;
}
bool AADLObjectIface::isRequired() const
{
    return direction() == IfaceType::Required;
}

QMap<AADLObjectIface::OperationKind, QString> AADLObjectIface::availableKindNames() const
{
    QMap<AADLObjectIface::OperationKind, QString> result;
    if (result.isEmpty()) {
        const QMetaEnum &me = QMetaEnum::fromType<ivm::AADLObjectIface::OperationKind>();
        for (int i = 0; i < me.keyCount(); ++i) {
            const AADLObjectIface::OperationKind k = static_cast<AADLObjectIface::OperationKind>(me.value(i));
            if ((isProvided() && k == OperationKind::Any) || (isRequired() && k == OperationKind::Cyclic)) {
                continue;
            }
            result.insert(k, QString(me.key(i)));
        }
    }
    return result;
}

QString AADLObjectIface::kindToString(AADLObjectIface::OperationKind k)
{
    const QMetaEnum &me = QMetaEnum::fromType<ivm::AADLObjectIface::OperationKind>();
    return QString::fromLatin1(me.valueToKey(static_cast<int>(k)));
}

AADLObjectIface::OperationKind AADLObjectIface::kindFromString(
        const QString &k, AADLObjectIface::OperationKind defaultKind)
{
    const QMetaEnum &me = QMetaEnum::fromType<ivm::AADLObjectIface::OperationKind>();
    bool ok = false;
    const auto kind = static_cast<AADLObjectIface::OperationKind>(me.keyToValue(k.toLatin1().data(), &ok));
    return ok ? kind : defaultKind;
}

AADLObjectIface::OperationKind AADLObjectIface::defaultKind() const
{
    return isProvided() ? OperationKind::Sporadic : OperationKind::Any;
}

/*! This returns the title. Unless it's an RI of type inherited, in which case it returns a comma
 * separated list of PI connected to it - unless none are and then it's back to title.
 */
QString AADLObjectIface::ifaceLabel() const
{
    return title();
}

AADLObjectIface::OperationKind AADLObjectIface::kindFromString(const QString &k) const
{
    return kindFromString(k, defaultKind());
}

AADLObjectIface::OperationKind AADLObjectIface::kind() const
{
    return this->kindFromString(attr(meta::Props::token(meta::Props::Token::kind)).toString());
}

bool AADLObjectIface::setKind(AADLObjectIface::OperationKind k)
{
    if (this->kind() != k) {
        setAttr(meta::Props::token(meta::Props::Token::kind), kindToString(k));
        return true;
    }

    return false;
}

QVector<IfaceParameter> AADLObjectIface::params() const
{
    return d->m_params;
}

IfaceParameter AADLObjectIface::param(const QString &name) const
{
    if (!name.isEmpty())
        for (const IfaceParameter &param : params())
            if (param.name() == name)
                return param;
    return {};
}

void AADLObjectIface::setParams(const QVector<IfaceParameter> &params)
{
    if (d->m_params != params) {
        d->m_params = params;
        Q_EMIT paramsChanged();
    }
}

void AADLObjectIface::addParam(const IfaceParameter &param)
{
    if (!d->m_params.contains(param)) {
        d->m_params.append(param);
        Q_EMIT paramsChanged();
    }
}

AADLObjectFunctionType *AADLObjectIface::function() const
{
    return qobject_cast<AADLObjectFunctionType *>(parentObject());
}

/*!
   Returns the parent functions, the grand parent function, ... as a list.
   The first function is the direct parent function
 */
QList<AADLObjectFunction *> AADLObjectIface::functionsStack() const
{
    QList<AADLObjectFunction *> result;
    AADLObjectFunction *parentFunc = qobject_cast<AADLObjectFunction *>(parentObject());
    while (parentFunc) {
        result.append(parentFunc);
        parentFunc = qobject_cast<AADLObjectFunction *>(parentFunc->parentObject());
    }
    return result;
}

AADLObjectIface *AADLObjectIface::cloneOf() const
{
    return d->m_cloneOf;
}

bool AADLObjectIface::isClone() const
{
    return nullptr != cloneOf();
}

bool AADLObjectIface::isCloned() const
{
    return d->m_clones.size();
}

QVector<QPointer<AADLObjectIface>> AADLObjectIface::clones() const
{
    return d->m_clones;
}

void AADLObjectIface::setCloneOrigin(AADLObjectIface *source)
{
    if (d->m_cloneOf != source) {
        d->m_cloneOf = source;
        if (d->m_cloneOf) {
            d->m_cloneOf->rememberClone(this);
        }
    }
}

void AADLObjectIface::rememberClone(AADLObjectIface *clone)
{
    if (clone && !d->m_clones.contains(clone)) {
        clone->cloneInternals(this);
        d->m_clones.append(clone);
    }
}

void AADLObjectIface::forgetClone(AADLObjectIface *clone)
{
    if (clone)
        clone->restoreInternals(this);
    d->m_clones.removeAll(clone);
}

AADLObjectIfaceProvided::AADLObjectIfaceProvided(const CreationInfo &ci)
    : AADLObjectIface(AADLObject::Type::ProvidedInterface, ci)
{
}

AADLObjectIfaceRequired::AADLObjectIfaceRequired(const CreationInfo &ci)
    : AADLObjectIface(AADLObject::Type::RequiredInterface, ci)
{
    setProp(meta::Props::token(meta::Props::Token::Autonamed), AADLNameValidator::isAutogeneratedName(this));
}

AADLObjectIface *AADLObjectIface::createIface(const CreationInfo &descr)
{
    AADLObjectIface *iface { nullptr };
    const bool isProvided = descr.type == AADLObjectIface::IfaceType::Provided;
    if (isProvided)
        iface = new AADLObjectIfaceProvided(descr);
    else
        iface = new AADLObjectIfaceRequired(descr);
    iface->setKind(descr.kind);

    return iface;
}

bool AADLObjectIface::storedKindDiffers() const
{
    const QString nameKind = meta::Props::token(meta::Props::Token::kind);
    return m_originalFields.attrs.value(nameKind) != attr(nameKind);
}

void AADLObjectIface::cloneInternals(const AADLObjectIface *from)
{
    if (!from)
        return;

    if (!m_originalFields.collected())
        m_originalFields.collect(isClone() ? d->m_cloneOf.data() : this);

    {
        QSignalBlocker sb(this);
        reflectAttrs(from);
        reflectProps(from);
        reflectParams(from);
    }

    if (storedKindDiffers())
        Q_EMIT attributeChanged(meta::Props::Token::kind);

    connect(from, qOverload<ivm::meta::Props::Token>(&AADLObjectIface::attributeChanged), this,
            &AADLObjectIface::onReflectedAttrChanged, Qt::UniqueConnection);
    connect(from, qOverload<ivm::meta::Props::Token>(&AADLObjectIface::propertyChanged), this,
            &AADLObjectIface::onReflectedPropChanged, Qt::UniqueConnection);
    connect(from, &AADLObjectIface::paramsChanged, this, &AADLObjectIface::onReflectedParamsChanged,
            Qt::UniqueConnection);
}

void AADLObjectIface::restoreInternals(const AADLObjectIface *disconnectMe)
{
    disconnect(disconnectMe, qOverload<ivm::meta::Props::Token>(&AADLObjectIface::attributeChanged), this,
            &AADLObjectIface::onReflectedAttrChanged);
    disconnect(disconnectMe, qOverload<ivm::meta::Props::Token>(&AADLObjectIface::propertyChanged), this,
            &AADLObjectIface::onReflectedPropChanged);
    disconnect(disconnectMe, &AADLObjectIface::paramsChanged, this, &AADLObjectIface::onReflectedParamsChanged);

    if (!m_originalFields.collected())
        return;

    // keep current coordinates:
    for (meta::Props::Token t : { meta::Props::Token::InnerCoordinates, meta::Props::Token::coordinates }) {
        const QString &name = meta::Props::token(t);
        if (m_originalFields.props.contains(name))
            m_originalFields.props[name] = prop(name);
    }

    const bool kindChanged = storedKindDiffers();

    {
        QSignalBlocker sb(this);

        setTitle(m_originalFields.name);
        setAttrs(m_originalFields.attrs);
        setProps(m_originalFields.props);
        setParams(m_originalFields.params);
    }

    if (kindChanged)
        Q_EMIT attributeChanged(meta::Props::Token::kind);

    m_originalFields = {};
}

QVariant AADLObjectIface::originalAttr(const QString &name) const
{
    return m_originalFields.attrs.value(name, QVariant());
}

QVariant AADLObjectIface::originalProp(const QString &name) const
{
    return m_originalFields.props.value(name, QVariant());
}

QVector<IfaceParameter> AADLObjectIface::originalParams() const
{
    return m_originalFields.params;
}

void AADLObjectIface::onReflectedAttrChanged(ivm::meta::Props::Token /*attr*/)
{
    if (AADLObjectIface *iface = qobject_cast<AADLObjectIface *>(sender()))
        reflectAttrs(iface);
}

void AADLObjectIface::onReflectedPropChanged(ivm::meta::Props::Token /*prop*/)
{
    if (AADLObjectIface *iface = qobject_cast<AADLObjectIface *>(sender()))
        reflectProps(iface);
}

void AADLObjectIface::onReflectedParamsChanged()
{
    if (AADLObjectIface *iface = qobject_cast<AADLObjectIface *>(sender()))
        reflectParams(iface);
}

void AADLObjectIface::reflectAttrs(const AADLObjectIface *from)
{
    if (!from)
        return;

    auto revertAttribute = [](const QString &name, QHash<QString, QVariant> &attrs,
                                   const QHash<QString, QVariant> &attrsOriginal) {
        const QVariant &value = attrsOriginal.value(name);
        if (value.isValid())
            attrs[name] = value;
    };

    QHash<QString, QVariant> newAttrs = from->attrs();

    const bool isFunctionTypeInherited = from->isNestedInFunctionType();
    const bool isInheritedName = (!isFunctionTypeInherited && isRequired() && from->isProvided());
    static const QString autonamedProp = meta::Props::token(meta::Props::Token::Autonamed);
    const bool isCustomName = !prop(autonamedProp).toBool() && !m_originalFields.props.value(autonamedProp).toBool();
    const bool keepName = isInheritedName || isCustomName;
    if (keepName)
        revertAttribute(meta::Props::token(meta::Props::Token::name), newAttrs, m_originalFields.attrs);

    setAttrs(newAttrs);
}

void AADLObjectIface::reflectProps(const AADLObjectIface *from)
{
    if (!from)
        return;

    auto revertProperty = [](meta::Props::Token t, QHash<QString, QVariant> &props,
                                  const QHash<QString, QVariant> &propsOriginal) {
        const QString &name = meta::Props::token(t);
        const QVariant &value = propsOriginal.value(name);
        if (value.isValid())
            props[name] = value;
    };

    const QHash<QString, QVariant> &currProps = props();
    QHash<QString, QVariant> newProps = from->props();
    const bool isFunctionTypeInherited = from->isNestedInFunctionType();

    for (auto t :
            { meta::Props::Token::InheritPI, meta::Props::Token::coordinates, meta::Props::Token::InnerCoordinates }) {
        const bool isInheritPIFlag = t == meta::Props::Token::InheritPI;
        const bool isInheritedPI = !isFunctionTypeInherited && isRequired() && from->isProvided();
        if (!isInheritPIFlag || isInheritedPI)
            revertProperty(t, newProps, currProps);
    }

    setProps(newProps);
}

void AADLObjectIface::reflectParams(const AADLObjectIface *from)
{
    if (!from)
        return;

    setParams(from->params());
}

void AADLObjectIfaceRequired::setAttr(const QString &name, const QVariant &val)
{
    if (!name.isEmpty()) {
        const meta::Props::Token t = meta::Props::token(name);
        switch (t) {
        case meta::Props::Token::name: {
            QString usedName = val.toString();
            if (usedName.isEmpty())
                usedName = AADLNameValidator::nextNameFor(this);

            const bool autoName = AADLNameValidator::isAutogeneratedName(this, usedName);

            static const QString autonamedPropName = meta::Props::token(meta::Props::Token::Autonamed);
            if (m_originalFields.collected()) {
                m_originalFields.props[autonamedPropName] = autoName;
                if (!autoName)
                    m_originalFields.attrs[name] = usedName;
            } else {
                setProp(autonamedPropName, autoName);
            }

            AADLObjectIface::setAttr(name, usedName);
            return;
        }
        default:
            break;
        }

        AADLObjectIface::setAttr(name, val);
    }
}

void AADLObjectIfaceRequired::setProp(const QString &name, const QVariant &val)
{
    if (!name.isEmpty()) {
        const meta::Props::Token t = meta::Props::token(name);
        switch (t) {
        case meta::Props::Token::InheritPI: {
            const bool newVal = val.toBool();
            if (prop(meta::Props::token(meta::Props::Token::InheritPI)) != newVal) {
                // should be handled in Connection _before_ the actual value change:
                Q_EMIT inheritedLabelsChanged(inheritedLables());

                AADLObject::setProp(name, val);
                Q_EMIT propChanged_InheritPI(newVal);
            }
            break;
        }
        default:
            AADLObject::setProp(name, val);
            break;
        }
    }
}

QStringList AADLObjectIfaceRequired::inheritedLables() const
{
    QStringList result;

    const QString &currentTitle = title();
    if (currentTitle != m_originalFields.name)
        result.append(currentTitle);
    else if (AADLNameValidator::isAutogeneratedName(this) && isInheritPI()) {
        result = collectInheritedLabels();

        // append suffix for connection to the same named PIs with same parent (Function.PI becomes Funtcion.PI#N)
        namesForRIToPIs(result);

        // if 2+ FnA.RI connected to the same FnB.PI, populate the inherited name with number suffix
        // (based on the index of the Connection among related connections)
        namesForRIsToPI(result);
    }

    if (result.isEmpty())
        result.append(currentTitle);

    return result;
}

QStringList AADLObjectIfaceRequired::collectInheritedLabels() const
{
    QStringList result, titles;
    std::transform(m_prototypes.cbegin(), m_prototypes.cend(), std::back_inserter(titles),
            [](const AADLObjectIfaceProvided *pi) { return pi->title(); });

    for (const AADLObjectIfaceProvided *pi : m_prototypes) {
        QString label = pi->title();
        if (titles.count(label) > 1) {
            Q_ASSERT(pi->parentObject());
            // if PIs have same name, prepend it with parent's name
            label = pi->parentObject()->title() + "." + label;
        }
        result.prepend(label);
    }
    return result;
}

void AADLObjectIfaceRequired::namesForRIToPIs(QStringList &result) const
{
    for (const QString &label : result) {
        int count = result.count(label);
        if (count > 1)
            while (count >= 1) {
                const int pos = result.indexOf(label);
                if (pos != -1)
                    result.replace(pos, label + "#" + QString::number(count));
                count = result.count(label);
            }
    }
}

void AADLObjectIfaceRequired::namesForRIsToPI(QStringList &result) const
{
    const AADLObjectFunctionType *parentFn = function();
    if (!parentFn)
        return;

    auto findRI = [](const AADLObjectConnection *in, const AADLObjectIfaceProvided *pi) -> AADLObjectIfaceRequired * {
        if (in && pi)
            for (AADLObjectIface *iface : { in->sourceInterface(), in->targetInterface() })
                if (iface && iface != pi && iface->isRequired())
                    return qobject_cast<AADLObjectIfaceRequired *>(iface);
        return nullptr;
    };

    const shared::Id &parentId = parentFn->id();
    for (const AADLObjectIfaceProvided *pi : m_prototypes) {
        const QVector<AADLObjectConnection *> &relatedConnecions = objectsModel()->getConnectionsForIface(pi->id());
        for (auto i = relatedConnecions.crbegin(); i != relatedConnecions.crend(); ++i) {
            AADLObjectConnection *c = *i;

            const bool sameSrcFn = c->source() && c->source()->id() == parentId;
            const bool sameDstFn = c->target() && c->target()->id() == parentId;
            const bool sameFn = sameSrcFn || sameDstFn;
            const bool isMeSrc = sameFn && c->sourceInterface() == this;
            const bool isMeDst = sameFn && c->targetInterface() == this;
            const bool toSibling = !isMeSrc && !isMeDst;
            if (toSibling)
                if (AADLObjectIfaceRequired *otherRI = findRI(c, pi)) {
                    if (!otherRI->isInheritPI())
                        continue;

                    const QString &oldLabel = pi->title();
                    const int labelPos = result.indexOf(oldLabel);
                    if (labelPos >= 0) {
                        result.replace(labelPos, oldLabel + "#" + QString::number(relatedConnecions.indexOf(c)));
                    }
                }
        }
    }
}

void AADLObjectIfaceRequired::setPrototype(const AADLObjectIfaceProvided *pi)
{
    if (!pi || !isInheritPI())
        return;

    if (!m_prototypes.contains(pi))
        m_prototypes.append(pi);

    if (!m_prototypes.isEmpty())
        cloneInternals(pi);

    Q_EMIT inheritedLabelsChanged(inheritedLables());
}

void AADLObjectIfaceRequired::unsetPrototype(const AADLObjectIfaceProvided *pi)
{
    if (!pi)
        return;

    m_prototypes.removeAll(pi);
    if (m_prototypes.isEmpty() || !isInheritPI())
        restoreInternals(pi);

    Q_EMIT inheritedLabelsChanged(inheritedLables());
}

QString AADLObjectIfaceRequired::ifaceLabel() const
{
    return ifaceLabelList().join(", ");
}

/*! Get the list of labels for this interface. It will either have the
 * inherited names or, if this is empty, the title. There will always
 * be at least one in the returned list.
 */
QStringList AADLObjectIfaceRequired::ifaceLabelList() const
{
    if (isInheritPI()) {
        const QStringList &labels = inheritedLables();
        if (!labels.isEmpty()) {
            return labels;
        }
    }
    return { AADLObjectIface::ifaceLabel() };
}

bool AADLObjectIfaceRequired::isInheritPI() const
{
    return prop(meta::Props::token(meta::Props::Token::InheritPI)).toBool();
}

bool AADLObjectIfaceRequired::hasPrototypePi() const
{
    return m_prototypes.size();
}

void AADLObjectIfaceRequired::cloneInternals(const AADLObjectIface *from)
{
    AADLObjectIface::cloneInternals(from);

    if (const AADLObjectIfaceRequired *ri = from->as<const AADLObjectIfaceRequired *>())
        connect(ri, &AADLObjectIfaceRequired::propChanged_InheritPI, this,
                &AADLObjectIfaceRequired::propChanged_InheritPI, Qt::UniqueConnection);
}

void AADLObjectIfaceRequired::restoreInternals(const AADLObjectIface *disconnectMe)
{
    AADLObjectIface::restoreInternals(disconnectMe);
    if (const AADLObjectIfaceRequired *ri = disconnectMe->as<const AADLObjectIfaceRequired *>())
        disconnect(ri, &AADLObjectIfaceRequired::propChanged_InheritPI, this,
                &AADLObjectIfaceRequired::propChanged_InheritPI);
}

}
