#!/bin/bash

SEDS_CONVERTER=$SPACECREATOR_BUILD_DIR/bin/sedsconverter
AADL_CONVERTER=$SPACECREATOR_BUILD_DIR/bin/aadlconverter
SPACE_CREATOR=/home/taste/tool-src/helper-scripts/space-creator
UPDATE_DATAVIEW=/home/taste/tool-src/helper-scripts/taste-update-data-view
ASN2DATAVIEW=asn2aadlPlus
TEST_OUTPUT_DIR=output

# Setup output dir and project
rm -r -f $TEST_OUTPUT_DIR
$SPACE_CREATOR init $TEST_OUTPUT_DIR
# Translate
$SEDS_CONVERTER --from SEDS --to InterfaceView --aux-models ASN.1 --skip-validation -i resources/test_hwas.xml \
  --out $TEST_OUTPUT_DIR/interfaceview.xml --iv-config config.xml --asn1-filepath-prefix $TEST_OUTPUT_DIR/ --acn-filepath-prefix $TEST_OUTPUT_DIR/
# Setup additional data
cp $TEST_OUTPUT_DIR/COM-N7SPACE-HWAS.asn $TEST_OUTPUT_DIR/output.asn
# Remove output ACN to avoid conflicts between the existing one and the ASN.1 file
# This cannot be replaced due to a reported bug in SEDS -> ASN.1 conversion
rm -f $TEST_OUTPUT_DIR/output.acn
# Rename the module to avoid naming conflicts
sed -i 's/COM-N7SPACE-HWAS/OUTPUT-DATAVIEW/g' $TEST_OUTPUT_DIR/output.asn
# Change implementation language to C
sed -i 's/language="SDL"/language="C"/g' $TEST_OUTPUT_DIR/interfaceview.xml

cd $TEST_OUTPUT_DIR
# Generate AADL
$UPDATE_DATAVIEW output.asn

$AADL_CONVERTER -o interfaceview.xml \
  -t /home/taste/tool-inst/share/xml2dv/interfaceview.tmplt \
  -x DeploymentView.aadl

$AADL_CONVERTER -o interfaceview.xml \
  -t /home/taste/tool-inst/share/xml2aadl/interfaceview.tmplt \
  -x InterfaceView.aadl

# Generate skeletons
make skeletons

# Make sure that the tested files exist and work correctly
# (existence of hwas.c ensures that interface view was handled correctly)
# diff is not extracted into a variable due to issues with escaping the regular expression
diff -w -B  -I "\* Generated by TASTE on .*" interfaceview.xml ../resources/test_hwas.interfaceview \
  && diff -w -B  -I "\* Generated by TASTE on .*" work/hwas/C/src/hwas.c ../resources/test_hwas.hwasc \
  && gcc -c -I work/dataview/C work/hwas/C/src/hwas.c \
  && cd .. \
  && rm -r -f $TEST_OUTPUT_DIR
