
/* Header file for function Pinger in GUI language
 * Generated by TASTE on 2022-05-24 17:24:57
 * Context Parameters present : NO
 * Provided interfaces : Poll
 * Required interfaces : IntegerInterface
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void pinger_startup(void);

/* Provided interfaces */
void pinger_PI_Poll( void );

/* Required interfaces */
extern void pinger_RI_IntegerInterface( const asn1SccMyBetterInteger * );


#ifdef __cplusplus
}
#endif

