/* ASN.1 System configuration file for function ModeManager
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */
#define __NEED_TInteger_NATIVE


#define __NEED_TInteger_NATIVE


#define __NEED_TConfig_NATIVE
#define __NEED_TInteger_NATIVE


#define __NEED_TReport_NATIVE
