SUBTYPE DEFINITIONS ::=
BEGIN


T-SmallInteger ::= INTEGER(0 | 10 | 100)

Egse-tc-cfg ::= SEQUENCE {
    param-a T-SmallInteger,
    param-b T-SmallInteger
}

Sensor-reading-x ::= T-SmallInteger

END
