all:
	mkdir -p code
	cd code && opengeode --toAda /home/taste/spacecreator/tests/manual/tmc/BasicCdrDemo/work/actuator/SDL/src/system_structure.pr "../actuator.pr"
	asn1scc -fp AUTO -typePrefix asn1Scc -o code -equal -Ada dataview-uniq.asn code/actuator_datamodel.asn
	cd code && gnat make actuator
clean:
	rm -rf code