FUNCTION-1-SUBTYPE DEFINITIONS ::=
BEGIN

IMPORTS MySeq FROM BASIC-ABSENT-DATAVIEW


MyChoice FROM BASIC-ABSENT-DATAVIEW

 ;




Function-1-pi-2-p1 ::= MySeq(WITH COMPONENTS(inputdata ABSENT))




Function-1-pi-1-p1 ::= MyChoice




END
