/* Body file for function controller
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "controller.h"

#include <stdio.h>
#include <math.h>
#include <string.h>

#include "tool_defines.h"
#include "comparison_defines.h"
#include "objects_of_sequence_data_types.h"
#include "objects_of_choice_data_types.h"
#include "objects_of_fixed_size_sequence_of_data_types.h"
#include "objects_of_variable_size_sequence_of_data_types.h"

void controller_startup(void)
{

}

// **********************************************************************
// Raport Functions

void reportAndExitFailure(const char* msg)
{
    printf("%s\n", msg);
    fflush(stdout);

    _Exit(EXIT_FAILURE);
}

void reportAndExitSuccess()
{
    printf("\n\n");
    printf("Tests Passed Successfully\n");
    fflush(stdout);

    _Exit(EXIT_SUCCESS);
}

// **********************************************************************
// TestCases

void aliasesTestCase()
{
    #ifdef TEST_CASE_NAME
    #undef TEST_CASE_NAME
    #endif

    #define TEST_CASE_NAME "aliasesTestCase"

    const asn1SccBoolAlias                 in1 = true;
    const asn1SccIntegerAlias              in2 = 100;
    const asn1SccRealAlias                 in3 = 0.5;
    const asn1SccIA5StringFixedSizeAlias   in4 = "ABC";
    const asn1SccIA5StringVarSizeAlias     in5 = "XY";
    const asn1SccOctetStringFixedSizeAlias in6 = {{'A', 'B', 'C'}};
    const asn1SccOctetStringVarSizeAlias   in7 = {2, {'X', 'Y'}};
    const asn1SccEnumAlias                 in8 = EnumAlias_zero;

    asn1SccBoolAlias                       out1;
    asn1SccIntegerAlias                    out2;
    asn1SccRealAlias                       out3;
    asn1SccIA5StringFixedSizeAlias         out4;
    asn1SccIA5StringVarSizeAlias           out5;
    asn1SccOctetStringFixedSizeAlias       out6;
    asn1SccOctetStringVarSizeAlias         out7;
    asn1SccEnumAlias                       out8;

    controller_RI_pi_aliasIface(&in1,  &in2,  &in3,  &in4,  &in5,  &in6,  &in7,  &in8,
                                &out1, &out2, &out3, &out4, &out5, &out6, &out7, &out8);

    if(in1 != out1) {
        reportAndExitFailure(GenerateComparisonFailureMsg(in1, out1));
    }

    if(in2 != out2) {
        reportAndExitFailure(GenerateComparisonFailureMsg(in2, out2));
    }

    if(fabs(in3 - out3) > 0.0001) {
        reportAndExitFailure(GenerateComparisonFailureMsg(in3, out3));
    }

    if(strcmp(in4, out4) != 0) {
        reportAndExitFailure(GenerateComparisonFailureMsg(in4, out4));
    }

    if(strcmp(in5, out5) != 0) {
        reportAndExitFailure(GenerateComparisonFailureMsg(in5, out5));
    }

    if(memcmp(&in6, &out6, 3) != 0) {
        reportAndExitFailure(GenerateComparisonFailureMsg(in6, out6));
    }

    if(memcmp(&in7, &out7, 2) != 0) {
        reportAndExitFailure(GenerateComparisonFailureMsg(in7, out7));
    }

    if(in8 != out8) {
        reportAndExitFailure(GenerateComparisonFailureMsg(in8, out8));
    }

    PrintTestPassedSuccessfully()
}

void sequencesTestCase()
{
    #ifdef TEST_CASE_NAME
    #undef TEST_CASE_NAME
    #endif

    #define TEST_CASE_NAME "sequencesTestCase"

    const asn1SccSeqAliases                            in1 = asn1SccSeqAliasesObj;
    const asn1SccSeqBuiltIn                            in2 = asn1SccSeqBuiltInObj;
    const asn1SccSeqOfFixedSizeSeqOfsProvidedInterface in3 = asn1SccSeqOfFixedSizeSeqOfsProvidedInterfaceObj;
    const asn1SccSeqOfVarSizeSeqOfsProvidedInterface   in4 = asn1SccSeqOfVarSizeSeqOfsProvidedInterfaceObj;
    const asn1SccSeqOfSeqsProvidedInterface            in5 =
    {
        in1,
        in2,
        in3,
        in4
    };
    const asn1SccSeqOfChoices                          in6 =
    {
        asn1SccChoiceAliasesObj,
        asn1SccChoiceBuiltInObj,
        asn1SccChoiceOfFixedSizeSeqOfsObj,
        asn1SccChoiceOfVarSizeSeqOfsObj
    };

    asn1SccSeqAliases              		               out1;
    asn1SccSeqBuiltIn                                  out2;
    asn1SccSeqOfFixedSizeSeqOfsProvidedInterface       out3;
    asn1SccSeqOfVarSizeSeqOfsProvidedInterface         out4;
    asn1SccSeqOfSeqsProvidedInterface                  out5;
    asn1SccSeqOfChoices                                out6;

    controller_RI_pi_seqIface(&in1,  &in2,  &in3,  &in4,  &in5,  &in6,
                              &out1, &out2, &out3, &out4, &out5, &out6);

    // in1, out1
    AliasesStructCompare(in1, out1)

    // in2, out2
    BuiltInStructCompare(in2, out2)

    // in3, out3
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(     3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeBoolAliasMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeBoolAliasMember)
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(     3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeIntegerAliasMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeIntegerAliasMember)
    FixedSizeSeqOfSeqOfSeqOfDoubleCompare(       3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeRealAliasMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeRealAliasMember)
    FixedSizeSeqOfSeqOfSeqOfStrCmpCompare(       3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeIA5StringFixedSizeAliasMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeIA5StringFixedSizeAliasMember)
    FixedSizeSeqOfSeqOfSeqOfStrCmpCompare(       3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeIA5StringVarSizeAliasMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeIA5StringVarSizeAliasMember)
    FixedSizeSeqOfSeqOfSeqOfMemCmpCompare(       3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeOctetStringFixedSizeAliasMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeOctetStringFixedSizeAliasMember)
    FixedSizeSeqOfSeqOfSeqOfMemCmpCompare(       3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeOctetStringVarSizeAliasMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeOctetStringVarSizeAliasMember)
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(     3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeEnumAliasMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeEnumAliasMember)
    FixedSizeSeqOfSeqOfSeqOfAliasesStructCompare(3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeSeqAliasesMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeSeqAliasesMember)
    FixedSizeSeqOfSeqOfSeqOfBuiltInStructCompare(3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeSeqBuiltInMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeSeqBuiltInMember)
    FixedSizeSeqOfSeqOfSeqOfAliasesChoiceCompare(3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeChoiceAliasesMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeChoiceAliasesMember)
    FixedSizeSeqOfSeqOfSeqOfBuiltInChoiceCompare(3,
                                                 in3.seqOfSeqOfSeqOfFixedSizeChoiceBuiltInMember,
                                                 out3.seqOfSeqOfSeqOfFixedSizeChoiceBuiltInMember)

    // in4, out4
    VarSizeSeqOfSeqOfSeqOfOperatorCompare(       2,
                                                 in4.seqOfSeqOfSeqOfVarSizeBoolAliasMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeBoolAliasMember)
    VarSizeSeqOfSeqOfSeqOfOperatorCompare(       2,
                                                 in4.seqOfSeqOfSeqOfVarSizeIntegerAliasMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeIntegerAliasMember)
    VarSizeSeqOfSeqOfSeqOfDoubleCompare(         2,
                                                 in4.seqOfSeqOfSeqOfVarSizeRealAliasMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeRealAliasMember)
    VarSizeSeqOfSeqOfSeqOfStrCmpCompare(         2,
                                                 in4.seqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAliasMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAliasMember)
    VarSizeSeqOfSeqOfSeqOfStrCmpCompare(         2,
                                                 in4.seqOfSeqOfSeqOfVarSizeIA5StringVarSizeAliasMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeIA5StringVarSizeAliasMember)
    VarSizeSeqOfSeqOfSeqOfMemCmpCompare(         2,
                                                 in4.seqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAliasMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAliasMember)
    VarSizeSeqOfSeqOfSeqOfMemCmpCompare(         2,
                                                 in4.seqOfSeqOfSeqOfVarSizeOctetStringVarSizeAliasMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeOctetStringVarSizeAliasMember)
     VarSizeSeqOfSeqOfSeqOfOperatorCompare(      2,
                                                 in4.seqOfSeqOfSeqOfVarSizeEnumAliasMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeEnumAliasMember)
    VarSizeSeqOfSeqOfSeqOfAliasesStructCompare(  2,
                                                 in4.seqOfSeqOfSeqOfVarSizeSeqAliasesMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeSeqAliasesMember)
    VarSizeSeqOfSeqOfSeqOfBuiltInStructCompare(  2,
                                                 in4.seqOfSeqOfSeqOfVarSizeSeqBuiltInMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeSeqBuiltInMember)
    VarSizeSeqOfSeqOfSeqOfAliasesChoiceCompare(  2,
                                                 in4.seqOfSeqOfSeqOfVarSizeChoiceAliasesMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeChoiceAliasesMember)
    VarSizeSeqOfSeqOfSeqOfBuiltInChoiceCompare(  2,
                                                 in4.seqOfSeqOfSeqOfVarSizeChoiceBuiltInMember,
                                                 out4.seqOfSeqOfSeqOfVarSizeChoiceBuiltInMember)

    // in5, out5
    AliasesStructCompare(in5.seqAliasesMember, out5.seqAliasesMember)
    BuiltInStructCompare(in5.seqBuiltInMember, out5.seqBuiltInMember)

    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(     3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeBoolAliasMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeBoolAliasMember)
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(     3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeIntegerAliasMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeIntegerAliasMember)
    FixedSizeSeqOfSeqOfSeqOfDoubleCompare(       3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeRealAliasMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeRealAliasMember)
    FixedSizeSeqOfSeqOfSeqOfStrCmpCompare(       3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeIA5StringFixedSizeAliasMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeIA5StringFixedSizeAliasMember)
    FixedSizeSeqOfSeqOfSeqOfStrCmpCompare(       3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeIA5StringVarSizeAliasMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeIA5StringVarSizeAliasMember)
    FixedSizeSeqOfSeqOfSeqOfMemCmpCompare(       3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeOctetStringFixedSizeAliasMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeOctetStringFixedSizeAliasMember)
    FixedSizeSeqOfSeqOfSeqOfMemCmpCompare(       3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeOctetStringVarSizeAliasMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeOctetStringVarSizeAliasMember)
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(     3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeEnumAliasMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeEnumAliasMember)
    FixedSizeSeqOfSeqOfSeqOfAliasesStructCompare(3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeSeqAliasesMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeSeqAliasesMember)
    FixedSizeSeqOfSeqOfSeqOfBuiltInStructCompare(3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeSeqBuiltInMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeSeqBuiltInMember)
    FixedSizeSeqOfSeqOfSeqOfAliasesChoiceCompare(3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeChoiceAliasesMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeChoiceAliasesMember)
    FixedSizeSeqOfSeqOfSeqOfBuiltInChoiceCompare(3,
                                                 in5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeChoiceBuiltInMember,
                                                 out5.seqOfFixedSizeSeqOfsMember.seqOfSeqOfSeqOfFixedSizeChoiceBuiltInMember)

    VarSizeSeqOfSeqOfSeqOfOperatorCompare(       2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeBoolAliasMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeBoolAliasMember)
    VarSizeSeqOfSeqOfSeqOfOperatorCompare(       2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeIntegerAliasMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeIntegerAliasMember)
    VarSizeSeqOfSeqOfSeqOfDoubleCompare(         2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeRealAliasMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeRealAliasMember)
    VarSizeSeqOfSeqOfSeqOfStrCmpCompare(         2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAliasMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAliasMember)
    VarSizeSeqOfSeqOfSeqOfStrCmpCompare(         2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeIA5StringVarSizeAliasMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeIA5StringVarSizeAliasMember)
    VarSizeSeqOfSeqOfSeqOfMemCmpCompare(         2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAliasMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAliasMember)
    VarSizeSeqOfSeqOfSeqOfMemCmpCompare(         2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeOctetStringVarSizeAliasMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeOctetStringVarSizeAliasMember)
    VarSizeSeqOfSeqOfSeqOfOperatorCompare(       2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeEnumAliasMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeEnumAliasMember)
    VarSizeSeqOfSeqOfSeqOfAliasesStructCompare(  2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeSeqAliasesMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeSeqAliasesMember)
    VarSizeSeqOfSeqOfSeqOfBuiltInStructCompare(  2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeSeqBuiltInMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeSeqBuiltInMember)
    VarSizeSeqOfSeqOfSeqOfAliasesChoiceCompare(  2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeChoiceAliasesMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeChoiceAliasesMember)
    VarSizeSeqOfSeqOfSeqOfBuiltInChoiceCompare(  2,
                                                 in5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeChoiceBuiltInMember,
                                                 out5.seqOfVarSizeSeqOfsMember.seqOfSeqOfSeqOfVarSizeChoiceBuiltInMember)

    // in6, out6
    AliasesChoiceCompare(in6.choiceAliasesMember, out6.choiceAliasesMember)
    BuiltInChoiceCompare(in6.choiceBuiltInMember, out6.choiceBuiltInMember)

    KindChoiceCompare(in6.choiceOfFixedSizeSeqOfsMember, out6.choiceOfFixedSizeSeqOfsMember)
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(3,
                                            in6.choiceOfFixedSizeSeqOfsMember.u.seqOfSeqOfSeqOfFixedSizeIntegerAliasMember,
                                            out6.choiceOfFixedSizeSeqOfsMember.u.seqOfSeqOfSeqOfFixedSizeIntegerAliasMember)

    KindChoiceCompare(in6.choiceOfVarSizeSeqOfsMember, out6.choiceOfVarSizeSeqOfsMember)
    VarSizeSeqOfSeqOfSeqOfOperatorCompare(3,
                                          in6.choiceOfVarSizeSeqOfsMember.u.seqOfSeqOfSeqOfVarSizeIntegerAliasMember,
                                          out6.choiceOfVarSizeSeqOfsMember.u.seqOfSeqOfSeqOfVarSizeIntegerAliasMember)

    PrintTestPassedSuccessfully()
}

void choicesTestCase()
{
    #ifdef TEST_CASE_NAME
    #undef TEST_CASE_NAME
    #endif

    #define TEST_CASE_NAME "choicesTestCase"

    const asn1SccChoiceAliases           in1 = asn1SccChoiceAliasesObj;
    const asn1SccChoiceBuiltIn           in2 = asn1SccChoiceBuiltInObj;
    const asn1SccChoiceOfFixedSizeSeqOfs in3 = asn1SccChoiceOfFixedSizeSeqOfsObj;
    const asn1SccChoiceOfVarSizeSeqOfs   in4 = asn1SccChoiceOfVarSizeSeqOfsObj;
    const asn1SccChoiceOfChoices         in5 =
    {
        ChoiceOfChoices_choiceBuiltInMember_PRESENT,
        {.choiceBuiltInMember = in2}
    };
    const asn1SccChoiceOfSeqs            in6 =
    {
        ChoiceOfSeqs_seqBuiltInMember_PRESENT,
        {.seqBuiltInMember = asn1SccSeqBuiltInObj}
    };

    asn1SccChoiceAliases                 out1;
    asn1SccChoiceBuiltIn                 out2;
    asn1SccChoiceOfFixedSizeSeqOfs       out3;
    asn1SccChoiceOfVarSizeSeqOfs         out4;
    asn1SccChoiceOfChoices               out5;
    asn1SccChoiceOfSeqs                  out6;

    controller_RI_pi_choiceIface(&in1,  &in2,  &in3,  &in4,  &in5,  &in6,
                                 &out1, &out2, &out3, &out4, &out5, &out6);

    // in1, out1
    AliasesChoiceCompare(in1, out1)

    // in2, out2
    BuiltInChoiceCompare(in2, out2)

    // in3, out3
    KindChoiceCompare(in3, out3)
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(3,
                                            in3.u.seqOfSeqOfSeqOfFixedSizeIntegerAliasMember,
                                            out3.u.seqOfSeqOfSeqOfFixedSizeIntegerAliasMember)

    // in4, out4
    KindChoiceCompare(in4, out4)
    VarSizeSeqOfSeqOfSeqOfOperatorCompare(2,
                                          in4.u.seqOfSeqOfSeqOfVarSizeIntegerAliasMember,
                                          out4.u.seqOfSeqOfSeqOfVarSizeIntegerAliasMember)

    // in5, out5
    KindChoiceCompare(in5, out5)
    BuiltInChoiceCompare(in5.u.choiceBuiltInMember, out5.u.choiceBuiltInMember)

    // in6, out6
    KindChoiceCompare(in6, out6)
    BuiltInStructCompare(in6.u.seqBuiltInMember, out6.u.seqBuiltInMember)

    PrintTestPassedSuccessfully()
}

void sequencesOfFixedSizeTestCase()
{
    #ifdef TEST_CASE_NAME
    #undef TEST_CASE_NAME
    #endif

    #define TEST_CASE_NAME "sequencesOfFixedSizeTestCase"

    const asn1SccSeqOfFixedSizeBoolAlias                            in1  = asn1SccSeqOfFixedSizeBoolAliasObj;
    const asn1SccSeqOfSeqOfFixedSizeBoolAlias                       in2  = asn1SccSeqOfSeqOfFixedSizeBoolAliasObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeBoolAlias                  in3  = asn1SccSeqOfSeqOfSeqOfFixedSizeBoolAliasObj;
    const asn1SccSeqOfFixedSizeIntegerAlias                         in4  = asn1SccSeqOfFixedSizeIntegerAliasObj;
    const asn1SccSeqOfSeqOfFixedSizeIntegerAlias                    in5  = asn1SccSeqOfSeqOfFixedSizeIntegerAliasObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeIntegerAlias               in6  = asn1SccSeqOfSeqOfSeqOfFixedSizeIntegerAliasObj;
    const asn1SccSeqOfFixedSizeRealAlias                            in7  = asn1SccSeqOfFixedSizeRealAliasObj;
    const asn1SccSeqOfSeqOfFixedSizeRealAlias                       in8  = asn1SccSeqOfSeqOfFixedSizeRealAliasObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeRealAlias                  in9  = asn1SccSeqOfSeqOfSeqOfFixedSizeRealAliasObj;
    const asn1SccSeqOfFixedSizeIA5StringFixedSizeAlias              in10 = asn1SccSeqOfFixedSizeIA5StringFixedSizeAliasObj;
    const asn1SccSeqOfSeqOfFixedSizeIA5StringFixedSizeAlias         in11 = asn1SccSeqOfSeqOfFixedSizeIA5StringFixedSizeAliasObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeIA5StringFixedSizeAlias    in12 = asn1SccSeqOfSeqOfSeqOfFixedSizeIA5StringFixedSizeAliasObj;
    const asn1SccSeqOfFixedSizeIA5StringVarSizeAlias                in13 = asn1SccSeqOfFixedSizeIA5StringVarSizeAliasObj;
    const asn1SccSeqOfSeqOfFixedSizeIA5StringVarSizeAlias           in14 = asn1SccSeqOfSeqOfFixedSizeIA5StringVarSizeAliasObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeIA5StringVarSizeAlias      in15 = asn1SccSeqOfSeqOfSeqOfFixedSizeIA5StringVarSizeAliasObj;
    const asn1SccSeqOfFixedSizeOctetStringFixedSizeAlias            in16 = asn1SccSeqOfFixedSizeOctetStringFixedSizeAliasObj;
    const asn1SccSeqOfSeqOfFixedSizeOctetStringFixedSizeAlias       in17 = asn1SccSeqOfSeqOfFixedSizeOctetStringFixedSizeAliasObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeOctetStringFixedSizeAlias  in18 = asn1SccSeqOfSeqOfSeqOfFixedSizeOctetStringFixedSizeAliasObj;
    const asn1SccSeqOfFixedSizeOctetStringVarSizeAlias              in19 = asn1SccSeqOfFixedSizeOctetStringVarSizeAliasObj;
    const asn1SccSeqOfSeqOfFixedSizeOctetStringVarSizeAlias         in20 = asn1SccSeqOfSeqOfFixedSizeOctetStringVarSizeAliasObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeOctetStringVarSizeAlias    in21 = asn1SccSeqOfSeqOfSeqOfFixedSizeOctetStringVarSizeAliasObj;
    const asn1SccSeqOfFixedSizeEnumAlias                            in22 = asn1SccSeqOfFixedSizeEnumAliasObj;
    const asn1SccSeqOfSeqOfFixedSizeEnumAlias                       in23 = asn1SccSeqOfSeqOfFixedSizeEnumAliasObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeEnumAlias                  in24 = asn1SccSeqOfSeqOfSeqOfFixedSizeEnumAliasObj;
    const asn1SccSeqOfFixedSizeSeqAliases                           in25 = asn1SccSeqOfFixedSizeSeqAliasesObj;
    const asn1SccSeqOfSeqOfFixedSizeSeqAliases                      in26 = asn1SccSeqOfSeqOfFixedSizeSeqAliasesObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeSeqAliases                 in27 = asn1SccSeqOfSeqOfSeqOfFixedSizeSeqAliasesObj;
    const asn1SccSeqOfFixedSizeSeqBuiltIn                           in28 = asn1SccSeqOfFixedSizeSeqBuiltInObj;
    const asn1SccSeqOfSeqOfFixedSizeSeqBuiltIn                      in29 = asn1SccSeqOfSeqOfFixedSizeSeqBuiltInObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeSeqBuiltIn                 in30 = asn1SccSeqOfSeqOfSeqOfFixedSizeSeqBuiltInObj;
    const asn1SccSeqOfFixedSizeChoiceAliases                        in31 = asn1SccSeqOfFixedSizeChoiceAliasesObj;
    const asn1SccSeqOfSeqOfFixedSizeChoiceAliases                   in32 = asn1SccSeqOfSeqOfFixedSizeChoiceAliasesObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeChoiceAliases              in33 = asn1SccSeqOfSeqOfSeqOfFixedSizeChoiceAliasesObj;
    const asn1SccSeqOfFixedSizeChoiceBuiltIn                        in34 = asn1SccSeqOfFixedSizeChoiceBuiltInObj;
    const asn1SccSeqOfSeqOfFixedSizeChoiceBuiltIn                   in35 = asn1SccSeqOfSeqOfFixedSizeChoiceBuiltInObj;
    const asn1SccSeqOfSeqOfSeqOfFixedSizeChoiceBuiltIn              in36 = asn1SccSeqOfSeqOfSeqOfFixedSizeChoiceBuiltInObj;

    asn1SccSeqOfFixedSizeBoolAlias								    out1;
    asn1SccSeqOfSeqOfFixedSizeBoolAlias							    out2;
    asn1SccSeqOfSeqOfSeqOfFixedSizeBoolAlias					    out3;
    asn1SccSeqOfFixedSizeIntegerAlias							    out4;
    asn1SccSeqOfSeqOfFixedSizeIntegerAlias						    out5;
    asn1SccSeqOfSeqOfSeqOfFixedSizeIntegerAlias					    out6;
    asn1SccSeqOfFixedSizeRealAlias								    out7;
    asn1SccSeqOfSeqOfFixedSizeRealAlias							    out8;
    asn1SccSeqOfSeqOfSeqOfFixedSizeRealAlias					    out9;
    asn1SccSeqOfFixedSizeIA5StringFixedSizeAlias				    out10;
    asn1SccSeqOfSeqOfFixedSizeIA5StringFixedSizeAlias			    out11;
    asn1SccSeqOfSeqOfSeqOfFixedSizeIA5StringFixedSizeAlias		    out12;
    asn1SccSeqOfFixedSizeIA5StringVarSizeAlias					    out13;
    asn1SccSeqOfSeqOfFixedSizeIA5StringVarSizeAlias				    out14;
    asn1SccSeqOfSeqOfSeqOfFixedSizeIA5StringVarSizeAlias		    out15;
    asn1SccSeqOfFixedSizeOctetStringFixedSizeAlias				    out16;
    asn1SccSeqOfSeqOfFixedSizeOctetStringFixedSizeAlias			    out17;
    asn1SccSeqOfSeqOfSeqOfFixedSizeOctetStringFixedSizeAlias	    out18;
    asn1SccSeqOfFixedSizeOctetStringVarSizeAlias				    out19;
    asn1SccSeqOfSeqOfFixedSizeOctetStringVarSizeAlias			    out20;
    asn1SccSeqOfSeqOfSeqOfFixedSizeOctetStringVarSizeAlias		    out21;
    asn1SccSeqOfFixedSizeEnumAlias								    out22;
    asn1SccSeqOfSeqOfFixedSizeEnumAlias							    out23;
    asn1SccSeqOfSeqOfSeqOfFixedSizeEnumAlias					    out24;
    asn1SccSeqOfFixedSizeSeqAliases								    out25;
    asn1SccSeqOfSeqOfFixedSizeSeqAliases						    out26;
    asn1SccSeqOfSeqOfSeqOfFixedSizeSeqAliases					    out27;
    asn1SccSeqOfFixedSizeSeqBuiltIn								    out28;
    asn1SccSeqOfSeqOfFixedSizeSeqBuiltIn						    out29;
    asn1SccSeqOfSeqOfSeqOfFixedSizeSeqBuiltIn					    out30;
    asn1SccSeqOfFixedSizeChoiceAliases							    out31;
    asn1SccSeqOfSeqOfFixedSizeChoiceAliases						    out32;
    asn1SccSeqOfSeqOfSeqOfFixedSizeChoiceAliases				    out33;
    asn1SccSeqOfFixedSizeChoiceBuiltIn							    out34;
    asn1SccSeqOfSeqOfFixedSizeChoiceBuiltIn						    out35;
    asn1SccSeqOfSeqOfSeqOfFixedSizeChoiceBuiltIn				    out36;

    controller_RI_pi_seqOfFixedSizeIface(
                                         &in1,   &in2,   &in3,
                                         &in4,   &in5,   &in6,
                                         &in7,   &in8,   &in9,
                                         &in10,  &in11,  &in12,
                                         &in13,  &in14,  &in15,
                                         &in16,  &in17,  &in18,
                                         &in19,  &in20,  &in21,
                                         &in22,  &in23,  &in24,
                                         &in25,  &in26,  &in27,
                                         &in28,  &in29,  &in30,
                                         &in31,  &in32,  &in33,
                                         &in34,  &in35,  &in36,

                                         &out1,  &out2,  &out3,
                                         &out4,  &out5,  &out6,
                                         &out7,  &out8,  &out9,
                                         &out10, &out11, &out12,
                                         &out13, &out14, &out15,
                                         &out16, &out17, &out18,
                                         &out19, &out20, &out21,
                                         &out22, &out23, &out24,
                                         &out25, &out26, &out27,
                                         &out28, &out29, &out30,
                                         &out31, &out32, &out33,
                                         &out34, &out35, &out36
                                        );

    FixedSizeSeqOfOperatorCompare(               3, in1,  out1)
    FixedSizeSeqOfSeqOfOperatorCompare(          3, in2,  out2)
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(     3, in3,  out3)

    FixedSizeSeqOfOperatorCompare(               3, in4,  out4)
    FixedSizeSeqOfSeqOfOperatorCompare(          3, in5,  out5)
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(     3, in6,  out6)

    FixedSizeSeqOfDoubleCompare(                 3, in7,  out7)
    FixedSizeSeqOfSeqOfDoubleCompare(            3, in8,  out8)
    FixedSizeSeqOfSeqOfSeqOfDoubleCompare(       3, in9,  out9)

    FixedSizeSeqOfStrCmpCompare(                 3, in10, out10)
    FixedSizeSeqOfSeqOfStrCmpCompare(            3, in11, out11)
    FixedSizeSeqOfSeqOfSeqOfStrCmpCompare(       3, in12, out12)

    FixedSizeSeqOfStrCmpCompare(                 3, in13, out13)
    FixedSizeSeqOfSeqOfStrCmpCompare(            3, in14, out14)
    FixedSizeSeqOfSeqOfSeqOfStrCmpCompare(       3, in15, out15)

    FixedSizeSeqOfMemCmpCompare(                 3, in16, out16)
    FixedSizeSeqOfSeqOfMemCmpCompare(            3, in17, out17)
    FixedSizeSeqOfSeqOfSeqOfMemCmpCompare(       3, in18, out18)

    FixedSizeSeqOfMemCmpCompare(                 3, in19, out19)
    FixedSizeSeqOfSeqOfMemCmpCompare(            3, in20, out20)
    FixedSizeSeqOfSeqOfSeqOfMemCmpCompare(       3, in21, out21)

    FixedSizeSeqOfOperatorCompare(               3, in22, out22)
    FixedSizeSeqOfSeqOfOperatorCompare(          3, in23, out23)
    FixedSizeSeqOfSeqOfSeqOfOperatorCompare(     3, in24, out24)

    FixedSizeSeqOfAliasesStructCompare(          3, in25, out25)
    FixedSizeSeqOfSeqOfAliasesStructCompare(     3, in26, out26)
    FixedSizeSeqOfSeqOfSeqOfAliasesStructCompare(3, in27, out27)

    FixedSizeSeqOfBuiltInStructCompare(          3, in28, out28)
    FixedSizeSeqOfSeqOfBuiltInStructCompare(     3, in29, out29)
    FixedSizeSeqOfSeqOfSeqOfBuiltInStructCompare(3, in30, out30)

    FixedSizeSeqOfAliasesChoiceCompare(          3, in31, out31)
    FixedSizeSeqOfSeqOfAliasesChoiceCompare(     3, in32, out32)
    FixedSizeSeqOfSeqOfSeqOfAliasesChoiceCompare(3, in33, out33)

    FixedSizeSeqOfBuiltInChoiceCompare(          3, in34, out34)
    FixedSizeSeqOfSeqOfBuiltInChoiceCompare(     3, in35, out35)
    FixedSizeSeqOfSeqOfSeqOfBuiltInChoiceCompare(3, in36, out36)

    PrintTestPassedSuccessfully()
}

void sequencesOfVariableSizeTestCase()
{
    #ifdef TEST_CASE_NAME
    #undef TEST_CASE_NAME
    #endif

    #define TEST_CASE_NAME "sequencesOfVariableSizeTestCase"

    const asn1SccSeqOfVarSizeBoolAlias                              in1  = asn1SccSeqOfVarSizeBoolAliasObj;
    const asn1SccSeqOfSeqOfVarSizeBoolAlias                         in2  = asn1SccSeqOfSeqOfVarSizeBoolAliasObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeBoolAlias                    in3  = asn1SccSeqOfSeqOfSeqOfVarSizeBoolAliasObj;
    const asn1SccSeqOfVarSizeIntegerAlias                           in4  = asn1SccSeqOfVarSizeIntegerAliasObj;
    const asn1SccSeqOfSeqOfVarSizeIntegerAlias                      in5  = asn1SccSeqOfSeqOfVarSizeIntegerAliasObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeIntegerAlias                 in6  = asn1SccSeqOfSeqOfSeqOfVarSizeIntegerAliasObj;
    const asn1SccSeqOfVarSizeRealAlias                              in7  = asn1SccSeqOfVarSizeRealAliasObj;
    const asn1SccSeqOfSeqOfVarSizeRealAlias                         in8  = asn1SccSeqOfSeqOfVarSizeRealAliasObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeRealAlias                    in9  = asn1SccSeqOfSeqOfSeqOfVarSizeRealAliasObj;
    const asn1SccSeqOfVarSizeIA5StringFixedSizeAlias                in10 = asn1SccSeqOfVarSizeIA5StringFixedSizeAliasObj;
    const asn1SccSeqOfSeqOfVarSizeIA5StringFixedSizeAlias           in11 = asn1SccSeqOfSeqOfVarSizeIA5StringFixedSizeAliasObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAlias      in12 = asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAliasObj;
    const asn1SccSeqOfVarSizeIA5StringVarSizeAlias                  in13 = asn1SccSeqOfVarSizeIA5StringVarSizeAliasObj;
    const asn1SccSeqOfSeqOfVarSizeIA5StringVarSizeAlias             in14 = asn1SccSeqOfSeqOfVarSizeIA5StringVarSizeAliasObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringVarSizeAlias        in15 = asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringVarSizeAliasObj;
    const asn1SccSeqOfVarSizeOctetStringFixedSizeAlias              in16 = asn1SccSeqOfVarSizeOctetStringFixedSizeAliasObj;
    const asn1SccSeqOfSeqOfVarSizeOctetStringFixedSizeAlias         in17 = asn1SccSeqOfSeqOfVarSizeOctetStringFixedSizeAliasObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAlias    in18 = asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAliasObj;
    const asn1SccSeqOfVarSizeOctetStringVarSizeAlias                in19 = asn1SccSeqOfVarSizeOctetStringVarSizeAliasObj;
    const asn1SccSeqOfSeqOfVarSizeOctetStringVarSizeAlias           in20 = asn1SccSeqOfSeqOfVarSizeOctetStringVarSizeAliasObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringVarSizeAlias      in21 = asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringVarSizeAliasObj;
    const asn1SccSeqOfVarSizeEnumAlias                              in22 = asn1SccSeqOfVarSizeEnumAliasObj;
    const asn1SccSeqOfSeqOfVarSizeEnumAlias                         in23 = asn1SccSeqOfSeqOfVarSizeEnumAliasObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeEnumAlias                    in24 = asn1SccSeqOfSeqOfSeqOfVarSizeEnumAliasObj;
    const asn1SccSeqOfVarSizeSeqAliases                             in25 = asn1SccSeqOfVarSizeSeqAliasesObj;
    const asn1SccSeqOfSeqOfVarSizeSeqAliases                        in26 = asn1SccSeqOfSeqOfVarSizeSeqAliasesObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeSeqAliases                   in27 = asn1SccSeqOfSeqOfSeqOfVarSizeSeqAliasesObj;
    const asn1SccSeqOfVarSizeSeqBuiltIn                             in28 = asn1SccSeqOfVarSizeSeqBuiltInObj;
    const asn1SccSeqOfSeqOfVarSizeSeqBuiltIn                        in29 = asn1SccSeqOfSeqOfVarSizeSeqBuiltInObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeSeqBuiltIn                   in30 = asn1SccSeqOfSeqOfSeqOfVarSizeSeqBuiltInObj;
    const asn1SccSeqOfVarSizeChoiceAliases                          in31 = asn1SccSeqOfVarSizeChoiceAliasesObj;
    const asn1SccSeqOfSeqOfVarSizeChoiceAliases                     in32 = asn1SccSeqOfSeqOfVarSizeChoiceAliasesObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeChoiceAliases                in33 = asn1SccSeqOfSeqOfSeqOfVarSizeChoiceAliasesObj;
    const asn1SccSeqOfVarSizeChoiceBuiltIn                          in34 = asn1SccSeqOfVarSizeChoiceBuiltInObj;
    const asn1SccSeqOfSeqOfVarSizeChoiceBuiltIn                     in35 = asn1SccSeqOfSeqOfVarSizeChoiceBuiltInObj;
    const asn1SccSeqOfSeqOfSeqOfVarSizeChoiceBuiltIn                in36 = asn1SccSeqOfSeqOfSeqOfVarSizeChoiceBuiltInObj;

    asn1SccSeqOfVarSizeBoolAlias                                    out1;
    asn1SccSeqOfSeqOfVarSizeBoolAlias                               out2;
    asn1SccSeqOfSeqOfSeqOfVarSizeBoolAlias                          out3;
    asn1SccSeqOfVarSizeIntegerAlias                                 out4;
    asn1SccSeqOfSeqOfVarSizeIntegerAlias                            out5;
    asn1SccSeqOfSeqOfSeqOfVarSizeIntegerAlias                       out6;
    asn1SccSeqOfVarSizeRealAlias                                    out7;
    asn1SccSeqOfSeqOfVarSizeRealAlias                               out8;
    asn1SccSeqOfSeqOfSeqOfVarSizeRealAlias                          out9;
    asn1SccSeqOfVarSizeIA5StringFixedSizeAlias                      out10;
    asn1SccSeqOfSeqOfVarSizeIA5StringFixedSizeAlias                 out11;
    asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringFixedSizeAlias            out12;
    asn1SccSeqOfVarSizeIA5StringVarSizeAlias                        out13;
    asn1SccSeqOfSeqOfVarSizeIA5StringVarSizeAlias                   out14;
    asn1SccSeqOfSeqOfSeqOfVarSizeIA5StringVarSizeAlias              out15;
    asn1SccSeqOfVarSizeOctetStringFixedSizeAlias                    out16;
    asn1SccSeqOfSeqOfVarSizeOctetStringFixedSizeAlias               out17;
    asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringFixedSizeAlias          out18;
    asn1SccSeqOfVarSizeOctetStringVarSizeAlias                      out19;
    asn1SccSeqOfSeqOfVarSizeOctetStringVarSizeAlias                 out20;
    asn1SccSeqOfSeqOfSeqOfVarSizeOctetStringVarSizeAlias            out21;
    asn1SccSeqOfVarSizeEnumAlias                                    out22;
    asn1SccSeqOfSeqOfVarSizeEnumAlias                               out23;
    asn1SccSeqOfSeqOfSeqOfVarSizeEnumAlias                          out24;
    asn1SccSeqOfVarSizeSeqAliases                                   out25;
    asn1SccSeqOfSeqOfVarSizeSeqAliases                              out26;
    asn1SccSeqOfSeqOfSeqOfVarSizeSeqAliases                         out27;
    asn1SccSeqOfVarSizeSeqBuiltIn                                   out28;
    asn1SccSeqOfSeqOfVarSizeSeqBuiltIn                              out29;
    asn1SccSeqOfSeqOfSeqOfVarSizeSeqBuiltIn                         out30;
    asn1SccSeqOfVarSizeChoiceAliases                                out31;
    asn1SccSeqOfSeqOfVarSizeChoiceAliases                           out32;
    asn1SccSeqOfSeqOfSeqOfVarSizeChoiceAliases                      out33;
    asn1SccSeqOfVarSizeChoiceBuiltIn                                out34;
    asn1SccSeqOfSeqOfVarSizeChoiceBuiltIn                           out35;
    asn1SccSeqOfSeqOfSeqOfVarSizeChoiceBuiltIn                      out36;

    controller_RI_pi_seqOfVariableSizeIface(
                                            &in1,   &in2,   &in3,
                                            &in4,   &in5,   &in6,
                                            &in7,   &in8,   &in9,
                                            &in10,  &in11,  &in12,
                                            &in13,  &in14,  &in15,
                                            &in16,  &in17,  &in18,
                                            &in19,  &in20,  &in21,
                                            &in22,  &in23,  &in24,
                                            &in25,  &in26,  &in27,
                                            &in28,  &in29,  &in30,
                                            &in31,  &in32,  &in33,
                                            &in34,  &in35,  &in36,

                                            &out1,  &out2,  &out3,
                                            &out4,  &out5,  &out6,
                                            &out7,  &out8,  &out9,
                                            &out10, &out11, &out12,
                                            &out13, &out14, &out15,
                                            &out16, &out17, &out18,
                                            &out19, &out20, &out21,
                                            &out22, &out23, &out24,
                                            &out25, &out26, &out27,
                                            &out28, &out29, &out30,
                                            &out31, &out32, &out33,
                                            &out34, &out35, &out36
                                           );

    VarSizeSeqOfOperatorCompare(               2, in1,  out1)
    VarSizeSeqOfSeqOfOperatorCompare(          2, in2,  out2)
    VarSizeSeqOfSeqOfSeqOfOperatorCompare(     2, in3,  out3)

    VarSizeSeqOfOperatorCompare(               2, in4,  out4)
    VarSizeSeqOfSeqOfOperatorCompare(          2, in5,  out5)
    VarSizeSeqOfSeqOfSeqOfOperatorCompare(     2, in6,  out6)

    VarSizeSeqOfDoubleCompare(                 2, in7,  out7)
    VarSizeSeqOfSeqOfDoubleCompare(            2, in8,  out8)
    VarSizeSeqOfSeqOfSeqOfDoubleCompare(       2, in9,  out9)

    VarSizeSeqOfStrCmpCompare(                 3, in10, out10)
    VarSizeSeqOfSeqOfStrCmpCompare(            3, in11, out11)
    VarSizeSeqOfSeqOfSeqOfStrCmpCompare(       3, in12, out12)

    VarSizeSeqOfStrCmpCompare(                 2, in13, out13)
    VarSizeSeqOfSeqOfStrCmpCompare(            2, in14, out14)
    VarSizeSeqOfSeqOfSeqOfStrCmpCompare(       2, in15, out15)

    VarSizeSeqOfMemCmpCompare(                 3, in16, out16)
    VarSizeSeqOfSeqOfMemCmpCompare(            3, in17, out17)
    VarSizeSeqOfSeqOfSeqOfMemCmpCompare(       3, in18, out18)

    VarSizeSeqOfMemCmpCompare(                 2, in19, out19)
    VarSizeSeqOfSeqOfMemCmpCompare(            2, in20, out20)
    VarSizeSeqOfSeqOfSeqOfMemCmpCompare(       2, in21, out21)

    VarSizeSeqOfOperatorCompare(               2, in22, out22)
    VarSizeSeqOfSeqOfOperatorCompare(          2, in23, out23)
    VarSizeSeqOfSeqOfSeqOfOperatorCompare(     2, in24, out24)

    VarSizeSeqOfAliasesStructCompare(          2, in25, out25)
    VarSizeSeqOfSeqOfAliasesStructCompare(     2, in26, out26)
    VarSizeSeqOfSeqOfSeqOfAliasesStructCompare(2, in27, out27)

    VarSizeSeqOfBuiltInStructCompare(          2, in28, out28)
    VarSizeSeqOfSeqOfBuiltInStructCompare(     2, in29, out29)
    VarSizeSeqOfSeqOfSeqOfBuiltInStructCompare(2, in30, out30)

    VarSizeSeqOfAliasesChoiceCompare(          2, in31, out31)
    VarSizeSeqOfSeqOfAliasesChoiceCompare(     2, in32, out32)
    VarSizeSeqOfSeqOfSeqOfAliasesChoiceCompare(2, in33, out33)

    VarSizeSeqOfBuiltInChoiceCompare(          2, in34, out34)
    VarSizeSeqOfSeqOfBuiltInChoiceCompare(     2, in35, out35)
    VarSizeSeqOfSeqOfSeqOfBuiltInChoiceCompare(2, in36, out36)

    PrintTestPassedSuccessfully()
}

// **********************************************************************
// Main Function

void controller_PI_trigger(void)
{
    printf("\n");

    aliasesTestCase();
    sequencesTestCase();
    choicesTestCase();
    sequencesOfFixedSizeTestCase();
    sequencesOfVariableSizeTestCase();

    reportAndExitSuccess();
}
