-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- (Generated by TASTE/Kazoo - $TOOL_SRC/kazoo/templates/glue/language_wrappers/simu_pi_adb/function.tmplt)
package body Controlsystem_PI is

   procedure Update_States_For_Synchronous_Calls (Global_State : asn1SccSystem_State) is
   begin
      --  No synchronous RIs are connected to this function
      null;
   end Update_States_For_Synchronous_Calls;

   procedure Update_Global_State_After_Synchronous_Calls (Global_State : in out asn1SccSystem_State)  is
   begin
      --  No synchronous RIs are connected to this function
      null;
   end Update_Global_State_After_Synchronous_Calls;

   procedure Startup (Global_State : in out asn1SccSystem_State) is
   begin
      --  Initialize the global state after startup function has run
      Global_State.Controlsystem := Controlsystem.Ctxt;
   end Startup;

   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State) is
   begin
      Controlsystem.Ctxt := Global_State.Controlsystem;
      Controlsystem.Execute_Transition (Controlsystem.CS_Only);
      Global_State.Controlsystem := Controlsystem.Ctxt;
   end Continuous_Signals;

   --  Provided interfaces
   procedure Configuration
      (Global_State : in out asn1SccSystem_State;
      Cfg : in out asn1SccPidconfig;
       Sender_PID : asn1SccPID := asn1SccEnv) is
   begin
      -- Set the current context (provided by the simulation API)
      Controlsystem.Ctxt := Global_State.Controlsystem;
      Controlsystem.Ctxt.Sender := Sender_PID;
      --  If user code calls synchronous RIs, set their state too
      Update_States_For_Synchronous_Calls (Global_State);
      Controlsystem.Configuration
         (Cfg => Cfg);
      -- Update the global state
      Global_State.Controlsystem := Controlsystem.Ctxt;
      --  If user code called synchronous RIs, populate their state
      Update_Global_State_After_Synchronous_Calls (Global_State);
   end Configuration;
   
   
   procedure Reading
      (Global_State : in out asn1SccSystem_State;
      Signalvalue : in out asn1SccNumber;
       Sender_PID : asn1SccPID := asn1SccEnv) is
   begin
      -- Set the current context (provided by the simulation API)
      Controlsystem.Ctxt := Global_State.Controlsystem;
      Controlsystem.Ctxt.Sender := Sender_PID;
      --  If user code calls synchronous RIs, set their state too
      Update_States_For_Synchronous_Calls (Global_State);
      Controlsystem.Reading
         (Signalvalue => Signalvalue);
      -- Update the global state
      Global_State.Controlsystem := Controlsystem.Ctxt;
      --  If user code called synchronous RIs, populate their state
      Update_Global_State_After_Synchronous_Calls (Global_State);
   end Reading;

end Controlsystem_PI;
