pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");


pragma Warnings (Off, "no entities of ""Basic_Types"" are referenced");
pragma Warnings (Off, "use clause for package ""Basic_Types"" has no effect");
with Basic_Types; use Basic_Types;
pragma Warnings (On, "no entities of ""Basic_Types"" are referenced");
pragma Warnings (On, "use clause for package ""Basic_Types"" has no effect");



package UART_DLC with SPARK_Mode
is


subtype asn1SccT_UART_DLC_Header is Basic_Types.asn1SccUINT8 range 22 .. 22;


function asn1SccT_UART_DLC_Header_Equal(val1, val2 : asn1SccT_UART_DLC_Header) return Boolean;

ERR_T_UART_DLC_HEADER_2:constant Integer := 231; -- (c-UART-DLC-SYNC-VALUE)
function asn1SccT_UART_DLC_Header_IsConstraintValid(val : asn1SccT_UART_DLC_Header) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_UART_DLC_Header_Init return asn1SccT_UART_DLC_Header;
subtype asn1SccT_UART_DLC_FrameCRC is Basic_Types.asn1SccUINT8 range 0 .. 255;


function asn1SccT_UART_DLC_FrameCRC_Equal(val1, val2 : asn1SccT_UART_DLC_FrameCRC) return Boolean;

ERR_T_UART_DLC_FRAMECRC_2:constant Integer := 237; -- 
function asn1SccT_UART_DLC_FrameCRC_IsConstraintValid(val : asn1SccT_UART_DLC_FrameCRC) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_UART_DLC_FrameCRC_Init return asn1SccT_UART_DLC_FrameCRC;
-- asn1SccT_RMAPCRCTable --------------------------------------------


subtype asn1SccT_RMAPCRCTable_index is Integer range 1..256;
type asn1SccT_RMAPCRCTable_array is array (asn1SccT_RMAPCRCTable_index) of Basic_Types.asn1SccUINT8;
type asn1SccT_RMAPCRCTable is  record
    Data  : asn1SccT_RMAPCRCTable_array;
end record;

function asn1SccT_RMAPCRCTable_Equal(val1, val2 : asn1SccT_RMAPCRCTable) return Boolean;

ERR_T_RMAPCRCTABLE:constant Integer := 301; -- (SIZE(256))
ERR_T_RMAPCRCTABLE_ELM_2:constant Integer := 296; -- 
function asn1SccT_RMAPCRCTable_IsConstraintValid(val : asn1SccT_RMAPCRCTable) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_RMAPCRCTable_Init return asn1SccT_RMAPCRCTable;
subtype asn1SccT_UART_DLC_FrameBuffer_index is Integer range 1..16;
subtype asn1SccT_UART_DLC_FrameBuffer_array is adaasn1rtl.OctetBuffer(asn1SccT_UART_DLC_FrameBuffer_index);
type asn1SccT_UART_DLC_FrameBuffer is  record
    Data  : asn1SccT_UART_DLC_FrameBuffer_array;
end record;

function asn1SccT_UART_DLC_FrameBuffer_Equal(val1, val2 : asn1SccT_UART_DLC_FrameBuffer) return Boolean;

ERR_T_UART_DLC_FRAMEBUFFER:constant Integer := 221; -- (SIZE(c-UART-DLC-PDU-SIZE ))
function asn1SccT_UART_DLC_FrameBuffer_IsConstraintValid(val : asn1SccT_UART_DLC_FrameBuffer) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_UART_DLC_FrameBuffer_Init return asn1SccT_UART_DLC_FrameBuffer;
subtype asn1SccT_UART_DLC_SDU_index is Integer range 1..14;
subtype asn1SccT_UART_DLC_SDU_array is adaasn1rtl.OctetBuffer(asn1SccT_UART_DLC_SDU_index);
type asn1SccT_UART_DLC_SDU is  record
    Data  : asn1SccT_UART_DLC_SDU_array;
end record;

function asn1SccT_UART_DLC_SDU_Equal(val1, val2 : asn1SccT_UART_DLC_SDU) return Boolean;

ERR_T_UART_DLC_SDU:constant Integer := 242; -- (SIZE(c-UART-DLC-SDU-SIZE))
function asn1SccT_UART_DLC_SDU_IsConstraintValid(val : asn1SccT_UART_DLC_SDU) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_UART_DLC_SDU_Init return asn1SccT_UART_DLC_SDU;
-- asn1SccT_UART_DLC_PDU --------------------------------------------

type asn1SccT_UART_DLC_PDU is record 
    dlc_header : asn1SccT_UART_DLC_Header;
    dlc_payload : asn1SccT_UART_DLC_SDU;
    crc : Basic_Types.asn1SccUINT8;
end record;


function asn1SccT_UART_DLC_PDU_Equal(val1, val2 : asn1SccT_UART_DLC_PDU) return Boolean;

ERR_T_UART_DLC_PDU:constant Integer := 281; -- 
ERR_T_UART_DLC_PDU_DLC_HEADER_2_2:constant Integer := 253; -- 
ERR_T_UART_DLC_PDU_DLC_PAYLOAD_2:constant Integer := 261; -- 
ERR_T_UART_DLC_PDU_CRC_2_2:constant Integer := 276; -- 
function asn1SccT_UART_DLC_PDU_IsConstraintValid(val : asn1SccT_UART_DLC_PDU) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_UART_DLC_PDU_Init return asn1SccT_UART_DLC_PDU;
subtype asn1SccT_UART_DLC_RxErrorCode_index_range is Integer range 0..4;
type asn1SccT_UART_DLC_RxErrorCode is (asn1Sccno_error, asn1Sccbad_start_char, asn1Scccrc_fail, asn1Sccframe_timeout, asn1Sccbad_request_type) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccT_UART_DLC_RxErrorCode use
    (asn1Sccno_error => 0, asn1Sccbad_start_char => 1, asn1Scccrc_fail => 2, asn1Sccframe_timeout => 3, asn1Sccbad_request_type => 4);

function asn1SccT_UART_DLC_RxErrorCode_Equal(val1, val2 : asn1SccT_UART_DLC_RxErrorCode) return Boolean;

ERR_T_UART_DLC_RXERRORCODE:constant Integer := 286; -- no-error | bad-start-char | crc-fail | frame-timeout | bad-request-type
function asn1SccT_UART_DLC_RxErrorCode_IsConstraintValid(val : asn1SccT_UART_DLC_RxErrorCode) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_UART_DLC_RxErrorCode_Init return asn1SccT_UART_DLC_RxErrorCode;
pragma Warnings (Off, "there are no others");
c_UART_DLC_SDU_SIZE : constant Basic_Types.asn1SccUINT8:= 14;
c_UART_DLC_PDU_SIZE : constant Basic_Types.asn1SccUINT8:= 16;
c_UART_DLC_SYNC_VALUE : constant Basic_Types.asn1SccUINT8:= 22;
c_RMAPCRCTable : constant UART_DLC.asn1SccT_RMAPCRCTable:= asn1SccT_RMAPCRCTable'(Data => asn1SccT_RMAPCRCTable_array'(1=>0, 2=>7, 3=>14, 4=>9, 
                                                            5=>28, 6=>27, 7=>18, 
                                                            8=>21, 9=>56, 10=>63, 
                                                            11=>54, 12=>49, 13=>36, 
                                                            14=>35, 15=>42, 16=>45, 
                                                            17=>112, 18=>119, 19=>126, 
                                                            20=>121, 21=>108, 22=>107, 
                                                            23=>98, 24=>101, 25=>72, 
                                                            26=>79, 27=>70, 28=>65, 
                                                            29=>84, 30=>83, 31=>90, 
                                                            32=>93, 33=>224, 34=>231, 
                                                            35=>238, 36=>233, 37=>252, 
                                                            38=>251, 39=>242, 40=>245, 
                                                            41=>216, 42=>223, 43=>214, 
                                                            44=>209, 45=>196, 46=>195, 
                                                            47=>202, 48=>205, 49=>144, 
                                                            50=>151, 51=>158, 52=>153, 
                                                            53=>140, 54=>139, 55=>130, 
                                                            56=>133, 57=>168, 58=>175, 
                                                            59=>166, 60=>161, 61=>180, 
                                                            62=>179, 63=>186, 64=>189, 
                                                            65=>199, 66=>192, 67=>201, 
                                                            68=>206, 69=>219, 70=>220, 
                                                            71=>213, 72=>210, 73=>255, 
                                                            74=>248, 75=>241, 76=>246, 
                                                            77=>227, 78=>228, 79=>237, 
                                                            80=>234, 81=>183, 82=>176, 
                                                            83=>185, 84=>190, 85=>171, 
                                                            86=>172, 87=>165, 88=>162, 
                                                            89=>143, 90=>136, 91=>129, 
                                                            92=>134, 93=>147, 94=>148, 
                                                            95=>157, 96=>154, 97=>39, 
                                                            98=>32, 99=>41, 100=>46, 
                                                            101=>59, 102=>60, 103=>53, 
                                                            104=>50, 105=>31, 106=>24, 
                                                            107=>17, 108=>22, 109=>3, 
                                                            110=>4, 111=>13, 112=>10, 
                                                            113=>87, 114=>80, 115=>89, 
                                                            116=>94, 117=>75, 118=>76, 
                                                            119=>69, 120=>66, 121=>111, 
                                                            122=>104, 123=>97, 124=>102, 
                                                            125=>115, 126=>116, 
                                                            127=>125, 128=>122, 
                                                            129=>137, 130=>142, 
                                                            131=>135, 132=>128, 
                                                            133=>149, 134=>146, 
                                                            135=>155, 136=>156, 
                                                            137=>177, 138=>182, 
                                                            139=>191, 140=>184, 
                                                            141=>173, 142=>170, 
                                                            143=>163, 144=>164, 
                                                            145=>249, 146=>254, 
                                                            147=>247, 148=>240, 
                                                            149=>229, 150=>226, 
                                                            151=>235, 152=>236, 
                                                            153=>193, 154=>198, 
                                                            155=>207, 156=>200, 
                                                            157=>221, 158=>218, 
                                                            159=>211, 160=>212, 
                                                            161=>105, 162=>110, 
                                                            163=>103, 164=>96, 165=>117, 
                                                            166=>114, 167=>123, 
                                                            168=>124, 169=>81, 170=>86, 
                                                            171=>95, 172=>88, 173=>77, 
                                                            174=>74, 175=>67, 176=>68, 
                                                            177=>25, 178=>30, 179=>23, 
                                                            180=>16, 181=>5, 182=>2, 
                                                            183=>11, 184=>12, 185=>33, 
                                                            186=>38, 187=>47, 188=>40, 
                                                            189=>61, 190=>58, 191=>51, 
                                                            192=>52, 193=>78, 194=>73, 
                                                            195=>64, 196=>71, 197=>82, 
                                                            198=>85, 199=>92, 200=>91, 
                                                            201=>118, 202=>113, 
                                                            203=>120, 204=>127, 
                                                            205=>106, 206=>109, 
                                                            207=>100, 208=>99, 209=>62, 
                                                            210=>57, 211=>48, 212=>55, 
                                                            213=>34, 214=>37, 215=>44, 
                                                            216=>43, 217=>6, 218=>1, 
                                                            219=>8, 220=>15, 221=>26, 
                                                            222=>29, 223=>20, 224=>19, 
                                                            225=>174, 226=>169, 
                                                            227=>160, 228=>167, 
                                                            229=>178, 230=>181, 
                                                            231=>188, 232=>187, 
                                                            233=>150, 234=>145, 
                                                            235=>152, 236=>159, 
                                                            237=>138, 238=>141, 
                                                            239=>132, 240=>131, 
                                                            241=>222, 242=>217, 
                                                            243=>208, 244=>215, 
                                                            245=>194, 246=>197, 
                                                            247=>204, 248=>203, 
                                                            249=>230, 250=>225, 
                                                            251=>232, 252=>239, 
                                                            253=>250, 254=>253, 
                                                            255=>244, 256=>243, others => 0)); 
pragma Warnings (On, "there are no others");
private
   --# hide UART_DLC;


end UART_DLC;