- hosts: localhost

- name: Include a play after another play
  import_playbook: prebuild.yml

- name: Copmile SpaceCreator
  hosts: localhost

  vars:
    env_qt_dir: "{{ env_dir }}/Qt/{{ env_qt_version }}/gcc_64/"
    install_dir: "{{ project_dir }}/install/"
    app_dir: "{{ env_dir }}/spacecreator.AppDir"
    app_lib_dir: "{{ app_dir }}/lib/Qt/lib"
    space_project_build_dir: "{{ project_dir }}/spacecreator_build_qt6"
    spacecreator_ninja_config_cmd: " cmake -GNinja  -S{{project_dir }} -B{{ space_project_build_dir }} -DCMAKE_BUILD_TYPE=Release -DBUILD_PATCH_NUMBER={{ patch_version }} -DCMAKE_PREFIX_PATH={{ env_qt_dir }}/lib/cmake/ -DQT_QMAKE_EXECUTABLE:STRING={{ env_qt_dir }}/bin/qmake -DQTC_INSTALL={{ app_dir }} -DQTC_SOURCE={{ app_dir }} -DBUILD_PLUGIN_ASN1=False -DENABLE_FORMAT_CHECK:BOOL=OFF"

  tasks:
    - name: "Extract libzxb-util to {{ app_lib_dir }}"
      unarchive:
        src: "{{ install_dir }}/libzxb-util.tar.gz"
        dest: "{{ app_lib_dir }}"

    - name: Copy additional Qt modules from "{{ app_lib_dir }} to "{{ env_qt_dir }}/lib"
      copy:
        src: "{{ item }}"
        dest: "{{ app_lib_dir }}"
        mode: 0755
      with_fileglob:
            - "{{ env_qt_dir }}/lib/libQt*WebSockets*"

    - name: Copy additional Additional AppImage files  "{{ install_dir }}/appimage" to "{{ app_dir }}"
      copy:
        src: "{{ item }}"
        dest: "{{ app_dir }}"
        mode: 0755
      with_fileglob:
            - "{{ install_dir }}/appimage/*"

    - name: "Config spacecreator in {{ space_project_build_dir }}"
      command:
        cmd: "{{ spacecreator_ninja_config_cmd }}"
        # creates: "{{ space_project_build_dir }}/build.ninja"

    - name: "Build spacecreator in {{ space_project_build_dir }}"
      command:
        cmd: "cmake --build {{ space_project_build_dir }} --target all"
        creates: "{{ space_project_build_dir }}/bin/IVeditor"
