-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
with Floatdemo_Dataview; use Floatdemo_Dataview;
with Taste_Basictypes;   use Taste_Basictypes;
with System_Dataview;    use System_Dataview;
with System_Dataview;     use System_Dataview;  -- PID type
with Simulation_Dataview; use Simulation_Dataview;
with Demo_Timer_Manager;

package Demo_Timer_Manager_PI is
   --  Interface to the simulation API
   procedure Startup (Global_State : in out asn1SccSystem_State);

   --  Stub for the Get_Sender function. Simulator does not need it as the sender
   --  is passed directly from the _Events to the _PI function and the state
   --  of the function is immediately updated with the value.
   procedure Dummy_Get_PID (Dummy_Param : asn1SccPID) is null
      with Export, Convention => C, Link_Name => "demo_timer_manager_get_sender";
   --  Execute only continuous signals (the simulator shall let the user
   --  send intermediate PIs in the queue since they have priority over
   --  continuous signals)
   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State);

   --  Provided interfaces
   procedure Reset_Sensor_Trigger (Global_State : in out asn1SccSystem_State;
                                  Sender_PID   : asn1SccPID := asn1SccEnv);
   
   
   procedure Set_Sensor_Trigger
      (Global_State : in out asn1SccSystem_State;
      Val : in out asn1SccT_Uint32;
       Sender_PID : asn1SccPID := asn1SccEnv);
   
   
   
   procedure Tick (Global_State : in out asn1SccSystem_State;
                                  Sender_PID   : asn1SccPID := asn1SccEnv);

end Demo_Timer_Manager_PI;
