SUBTYPES DEFINITIONS ::=
BEGIN

-- Tailored-Byte ::= INTEGER(0 | 10 | 255) 

-- Bcapp-dlctxsdu-p1 ::= SEQUENCE (SIZE(2)) OF Tailored-Byte

Bcapp-dlctxsdu-p1 ::= OCTET STRING (SIZE(2))


Channeleffects-corruptchar-p1 ::= INTEGER(1 | 15)


END

