// Autogenerated code (from TASTE/Kazoo) : DO NOT EDIT

#include "demo_timer_manager.h"

// When rtdlcr_FrameTimer expires, this function is called:
extern void demo_timer_manager_RI_rtdlcr_FrameTimer(void);

void demo_timer_manager_startup(void)
{
 // Timer start up (nothing to do)
}

void demo_timer_manager_PI_Tick(void)
{
   if (active == timers[rtdlcr_FrameTimer].state && 0 == -- timers[rtdlcr_FrameTimer].value) {
      demo_timer_manager_RI_rtdlcr_FrameTimer();
      timers[rtdlcr_FrameTimer].state = inactive;
   }

}

void demo_timer_manager_PI_SET_rtdlcr_FrameTimer(asn1SccT_UInt32 *val)
{
   /* Timer value must be multiple of 10 ms */
   assert (0 == (*val % 10));
   timers[rtdlcr_FrameTimer].state = active;
   timers[rtdlcr_FrameTimer].value = *val / 10;
}

void demo_timer_manager_PI_RESET_rtdlcr_FrameTimer(void)
{
   timers[rtdlcr_FrameTimer].state = inactive;
}


