#!/bin/sh

export _ORIGINAL_LD_LIBRARY_PATH=$LD_LIBRARY_PATH

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/i386-linux-gnu/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib32/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib/i386-linux-gnu/:${HERE}/lib/x86_64-linux-gnu/:${HERE}/lib32/:${HERE}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export GSETTINGS_SCHEMA_DIR="${HERE}/usr/share/glib-2.0/schemas/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"

usage()
{
   cat <<EOF
Usage: spaceCreator [OPTIONS]
Options:
        No option:
            Start space creator
        [--aadlconverter [--help]]
            Run the aadlconverter
        [--dvconverter [--help]]
            Run the dvconverter
        [--mscconverter [--help]]
            Run the mscconverter
        [--sedsconverter [--help]]
            Run the sedsconverter
        [--tmcconverter [--help]]
            Run the TMC converter
        [--tmcivoptimizer [--help]]
            Run the TMC Interface View optimizer
        [--ivmerger [--help]]
            Run the InterfaceView merger
        [--ivstreaming [--help]]
            Run the InterfaceView UI streaming client
        [--mscstreaming [--help]]
            Run the mscstreaming
        [--e2eimagesaver [--help]]
            Run the End-to-End View diagram saver
        [--DVeditor [--help]]
            Run the DVeditor
        [--IVeditor [--help]]
            Run the IVeditor
        [--MSCeditor [--help]]
            Run the MSC editor
        [--qhelpgenerator [--help]]
            Run the QHelpGenerator
        [--trailgen [--help]]
            Run the trailgen
        [--help]
            Output this message
        [--version]
            Print version information
EOF
}


bindir=${HERE}/bin
libdir=`cd "${HERE}/lib" ; pwd`
# Add path to deployed Qt libraries in package
qtlibdir=$libdir/Qt/lib
if test -d "$qtlibdir"; then
    qtlibpath=$qtlibdir
fi
libexecdir=${HERE}/libexec
# Add Qt Creator library path
LD_LIBRARY_PATH=$libdir:$libdir/qtcreator:$qtlibpath:$qtlibpath/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

TOOL=$1

case $TOOL in
--help|-h)
    usage 1>&2
    exit 1
    ;;
--aadlconverter)
    shift
    exec "$bindir/aadlconverter" $@
    ;;
--dvconverter)
    shift
    exec "$bindir/dvconverter" $@
    ;;
--mscconverter)
    shift
    exec "$bindir/mscconverter" $@
    ;;
--sedsconverter)
    shift
    exec "$bindir/sedsconverter" $@
    ;;
--tmcconverter)
    shift
    exec "$bindir/tmc" $@
    ;;
--tmcivoptimizer)
    shift
    exec "$bindir/tmcivoptimizer" $@
    ;;
--ivmerger)
    shift
    exec "$bindir/ivmerger" $@
    ;;
--ivstreaming)
    shift
    exec "$bindir/ivstreaming" $@
    ;;
--mscstreaming)
    shift
    exec "$bindir/mscstreaming" $@
    ;;
--e2eimagesaver)
    shift
    exec "$bindir/e2eimagesaver" $@
    ;;
--DVeditor)
    shift
    exec "$bindir/DVeditor" $@
    ;;
--IVeditor)
    shift
    exec "$bindir/IVeditor" $@
    ;;
--MSCeditor)
    shift
    exec "$bindir/msceditor" $@
    ;;
--qhelpgenerator)
    shift
    exec "$libexecdir/qhelpgenerator" $@
    ;;
--trailgen)
    shift
    exec "$bindir/trailgen" $@
    ;;
--version|-version)
    "$bindir/qtcreator" -user-library-path "$_ORIGINAL_LD_LIBRARY_PATH" "-version"
    exec $bindir/IVeditor "--version"
    ;;
*)
    exec "$bindir/qtcreator" -user-library-path "$_ORIGINAL_LD_LIBRARY_PATH" ${1+"$@"} -color blue
    ;;
esac
