#!/bin/sh

export _ORIGINAL_LD_LIBRARY_PATH=$LD_LIBRARY_PATH

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
#export PATH="${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}"
#export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/i386-linux-gnu/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib32/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib/i386-linux-gnu/:${HERE}/lib/x86_64-linux-gnu/:${HERE}/lib32/:${HERE}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
#export PYTHONPATH="${HERE}/usr/share/pyshared/${PYTHONPATH:+:$PYTHONPATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
#export PERLLIB="${HERE}/usr/share/perl5/:${HERE}/usr/lib/perl5/${PERLLIB:+:$PERLLIB}"
export GSETTINGS_SCHEMA_DIR="${HERE}/usr/share/glib-2.0/schemas/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
#export QT_PLUGIN_PATH="${HERE}/usr/lib/qt5/plugins/:${HERE}/usr/lib/i386-linux-gnu/qt5/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/qt5/plugins/:${HERE}/usr/lib32/qt5/plugins/:${HERE}/usr/lib64/qt5/plugins/${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}"

usage()
{
   cat <<EOF
Usage: qtcreator [OPTIONS]
Options:
        No option:
            Start space creator
        [--aadlconverter [--help]]
            Run the aadlconverter
        [--dvconverter [--help]]
            Run the dvconverter
        [--mscconverter [--help]]
            Run the mscconverter
        [--mscstreaming [--help]]
            Run the mscstreaming
        [--DVeditor [--help]]
            Run the DVeditor
        [--IVeditor [--help]]
            Run the IVeditor
        [--MSCeditor [--help]]
            Run the MSC editor
        [--help]
            Output this message
        [--version]
            Print version information
EOF
}


bindir=${HERE}/bin
libdir=`cd "${HERE}/lib" ; pwd`
# Add path to deployed Qt libraries in package
qtlibdir=$libdir/Qt/lib
if test -d "$qtlibdir"; then
    qtlibpath=:$qtlibdir
fi
# Add Qt Creator library path
LD_LIBRARY_PATH=$libdir:$libdir/qtcreator$qtlibpath${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export LD_LIBRARY_PATH


case $1 in
--help|-h)
    usage 1>&2
    exit 1
    ;;
--aadlconverter)
    exec "$bindir/aadlconverter" "$2" "$3" "$4" "$5" "$6" "$7"
    ;;
--dvconverter)
    exec "$bindir/dvconverter" "$2" "$3" "$4" "$5" "$6" "$7"
    ;;
--mscconverter)
    exec "$bindir/mscconverter" "$2" "$3" "$4" "$5" "$6" "$7"
    ;;
--mscstreaming)
    exec "$bindir/mscstreaming" "$2" "$3" "$4" "$5" "$6" "$7"
    ;;
--DVeditor)
    exec "$bindir/DVeditor" "$2" "$3" "$4" "$5" "$6" "$7"
    ;;
--IVeditor)
    exec "$bindir/IVeditor" "$2" "$3" "$4" "$5" "$6" "$7"
    ;;
--MSCeditor)
    exec "$bindir/msceditor" "$2" "$3" "$4" "$5" "$6" "$7"
    ;;
    "$bindir/qtcreator" -user-library-path "$_ORIGINAL_LD_LIBRARY_PATH" "-version"
    exec $bindir/IVeditor "--version"
    ;;
*)
    exec "$bindir/qtcreator" -user-library-path "$_ORIGINAL_LD_LIBRARY_PATH" ${1+"$@"}
    ;;
esac
