-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-09-30 02:04:18
with Simulator;            use Simulator;
with Simulation_Dataview;  use Simulation_Dataview;
with System_Dataview;      use System_Dataview;
package body Bcdlct_RI is

   procedure Phytxchar
      (P1 : in out asn1SccUint8) is
      --  Generate an event to the simulator for the output
      Event_Out_Erroredchannel : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_Erroredchannel.Output_Event :=
        (Source => asn1sccBcdlct,
         Dest   => asn1sccErroredchannel,
         Event  => (Kind => Bcdlct_PRESENT,
                    Bcdlct =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Phytxchar_PRESENT,
                     Phytxchar =>
                           (P1 => P1)))));
      Push_Event (Event_Out_Erroredchannel);
   
   end Phytxchar;

end Bcdlct_RI;
