/* Header file for function Utils
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void utils_startup(void);

/* Provided interfaces */
void utils_PI_Stub( const asn1SccMyInteger *, asn1SccMyInteger * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
