Right-Datamodel DEFINITIONS ::=
BEGIN
IMPORTS
   MyInteger FROM INPUTVECTORLIMIT-DATAVIEW
   T-Int32, T-UInt32, T-Int8, T-UInt8, T-Boolean, T-Null-Record FROM TASTE-BasicTypes;

Right-States ::= ENUMERATED {wait}

Right-Context ::= SEQUENCE {
   state Right-States,
   init-done BOOLEAN,
   rightarg MyInteger,
   rightval MyInteger
}

END
