/* Body file for function RTDLCR
 * Generated by TASTE on 2022-09-30 02:17:32
 */
#include "rtdlcr_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);



extern void adainit(void);

extern void init_demo_timer_manager(void);
extern unsigned demo_timer_manager_initialized;
#include "demo_timer_manager_vm_if.h"
extern void init_demo_timer_manager(void);
extern unsigned demo_timer_manager_initialized;
#include "demo_timer_manager_vm_if.h"
unsigned rtdlcr_initialized = 0;
void init_rtdlcr(void)
{
   if (0 == rtdlcr_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      rtdlcr_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == demo_timer_manager_initialized) {
          init_demo_timer_manager();
      }
      if (0 == demo_timer_manager_initialized) {
          init_demo_timer_manager();
      }
      puts ("[TASTE] Initialization completed for function RTDLCR");
      rtdlcr_initialized = 2;
   }
}
void rtdlcr_DLCRxReset()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: rtdlcr,dlcrxreset,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void rtdlcr_PI_DLCRxReset(void);
   rtdlcr_PI_DLCRxReset();
   // puts ("rtdlcr_dlcrxreset called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *rtdlcr_state(void);
      printf ("INNER_SDL_STATE: rtdlcr,%s\n", rtdlcr_state());
      fflush(stdout);
   }
}




void rtdlcr_FrameTimer()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: rtdlcr,frametimer,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void rtdlcr_PI_FrameTimer(void);
   rtdlcr_PI_FrameTimer();
   // puts ("rtdlcr_frametimer called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *rtdlcr_state(void);
      printf ("INNER_SDL_STATE: rtdlcr,%s\n", rtdlcr_state());
      fflush(stdout);
   }
}




void rtdlcr_PHYRxChar
      (const char *IN_p1, size_t IN_p1_len)

{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: rtdlcr,phyrxchar,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void rtdlcr_PI_PHYRxChar
      (const asn1SccUINT8 *);





   // Call user code
   rtdlcr_PI_PHYRxChar ((asn1SccUINT8 *)IN_p1);

   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *rtdlcr_state(void);
      printf ("INNER_SDL_STATE: rtdlcr,%s\n", rtdlcr_state());
      fflush(stdout);
   }
}




void rtdlcr_PHYRxError()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: rtdlcr,phyrxerror,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void rtdlcr_PI_PHYRxError(void);
   rtdlcr_PI_PHYRxError();
   // puts ("rtdlcr_phyrxerror called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *rtdlcr_state(void);
      printf ("INNER_SDL_STATE: rtdlcr,%s\n", rtdlcr_state());
      fflush(stdout);
   }
}

