FUNCTION-1-SUBTYPE DEFINITIONS ::=
BEGIN

IMPORTS MyChoice FROM CHOICE-ABSENT-DATAVIEW


MySeq FROM CHOICE-ABSENT-DATAVIEW

 ;

MySeqSub ::= MySeq (WITH COMPONENTS { inputdata ABSENT })

Function-1-pi-1-p1 ::= MySeqSub

END
