/* Body file for function CImplSeq
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "cimplseq.h"
#include <string.h>

void cimplseq_startup(void)
{

}

void cimplseq_PI_ri_seqIface
      (const asn1SccSeqAliases *IN_i1,
       const asn1SccSeqBuiltIn *IN_i2,
       const asn1SccSeqOfFixedSizeSeqOfsRequiredInterface *IN_i3,
       const asn1SccSeqOfVarSizeSeqOfsRequiredInterface *IN_i4,
       const asn1SccSeqOfSeqsRequiredInterface *IN_i5,

       asn1SccSeqAliases *OUT_o1,
       asn1SccSeqBuiltIn *OUT_o2,
       asn1SccSeqOfFixedSizeSeqOfsRequiredInterface *OUT_o3,
       asn1SccSeqOfVarSizeSeqOfsRequiredInterface *OUT_o4,
       asn1SccSeqOfSeqsRequiredInterface *OUT_o5)

{
    memcpy(OUT_o1, IN_i1, sizeof(asn1SccSeqAliases));
    memcpy(OUT_o2, IN_i2, sizeof(asn1SccSeqBuiltIn));
    memcpy(OUT_o3, IN_i3, sizeof(asn1SccSeqOfFixedSizeSeqOfsRequiredInterface));
    memcpy(OUT_o4, IN_i4, sizeof(asn1SccSeqOfVarSizeSeqOfsRequiredInterface));
    memcpy(OUT_o5, IN_i5, sizeof(asn1SccSeqOfSeqsRequiredInterface));
}
