/* Body file for function Clock
 * Generated by TASTE on 2022-05-16 12:07:46
 * Provided interfaces : Poll
 * Required interfaces : ClockInterface
 * User-defined properties for this function:
 * Timers              : 
 */
#include "clock_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
   extern long long getTimeInMilliseconds(void);
#endif




unsigned clock_initialized = 0;
void init_clock(void)
{
   if (0 == clock_initialized) {
      #ifdef __unix__
         // Initialize epoch for the MSC tracing in debug mode
         long long unused = getTimeInMilliseconds();
      #endif
      clock_initialized = 1;
      // Call user code startup function
      extern void clock_startup(void);
      clock_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function Clock");
#endif
      clock_initialized = 2;
   }
}
void clock_Poll()
{

   //  Directly call user code, no parameters to pass
   extern void clock_PI_Poll(void);
   clock_PI_Poll();
   // puts ("clock_poll called");
}

