-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- (Generated by TASTE/Kazoo - $TOOL_SRC/kazoo/templates/glue/language_wrappers/simu_pi_adb/function.tmplt)
with actuator;
with controller;
package body Gui_PI is

   procedure Update_States_For_Synchronous_Calls (Global_State : asn1SccSystem_State) is
   begin
      actuator.Ctxt := Global_State.actuator;
      controller.Ctxt := Global_State.controller;
   end Update_States_For_Synchronous_Calls;

   procedure Update_Global_State_After_Synchronous_Calls (Global_State : in out asn1SccSystem_State)  is
   begin
      Global_State.actuator := actuator.Ctxt;
      Global_State.controller := controller.Ctxt;
   end Update_Global_State_After_Synchronous_Calls;

   procedure Startup (Global_State : in out asn1SccSystem_State) is
   begin
      --  Initialize the global state after startup function has run
      Global_State.Gui := Gui.Ctxt;
   end Startup;

   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State) is
   begin
      Gui.Ctxt := Global_State.Gui;
      Gui.Execute_Transition (Gui.CS_Only);
      Global_State.Gui := Gui.Ctxt;
   end Continuous_Signals;

   --  Provided interfaces
   procedure If3 (Global_State : in out asn1SccSystem_State) is
   begin
      -- Set the current context (provided by the simulation API)
      Gui.Ctxt := Global_State.Gui;
      --  If user code calls synchronous RIs, set their state too
      Update_States_For_Synchronous_Calls (Global_State);
      Gui.If3;
      -- Update the global state
      Global_State.Gui := Gui.Ctxt;
      --  If user code called synchronous RIs, populate their state
      Update_Global_State_After_Synchronous_Calls (Global_State);
   end If3;

end Gui_PI;
