/* Message identifiers for the GUI messages
 * Used by the code of the GUIs and by the ctypes Python interface
 * DO NOT EDIT THIS FILE MANUALLY - MODIFY THE KAZOO TEMPLATE IF NECESSARY
*/
#pragma once

// 3 dlcrxerror, dlcrxsdu, poll
typedef enum {
   i_DLCRxError,
   i_DLCRxSDU
} T_rtapp_PI_list;

typedef enum {
   i_DLCRxReset
} T_rtapp_RI_list;

