COM-N7SPACE-COMMANDARGUMENTS DEFINITIONS ::= BEGIN
MyInteger ::= INTEGER(0 .. 255)
MyFloat ::= REAL(-3.40282e+38 .. 3.40282e+38)
AsyncInterface-AsyncInCommand-Type ::= SEQUENCE
{
    asyncInArgument1 MyInteger(0 .. 255),
    asyncInArgument2 MyInteger(0 .. 255)
}
AsyncInterface-AsyncOutCommand-Type ::= SEQUENCE
{
    asyncOutArgument1 MyInteger(0 .. 255),
    asyncOutArgument2 MyInteger(0 .. 255)
}
MyIntegerArray-10 ::= SEQUENCE (SIZE(10)) OF MyInteger(0 .. 255)
ArrayInterface-ArrayCommand1-Type ::= SEQUENCE
{
    arrayArgument1 MyIntegerArray-10(SIZE(10))
}
MyIntegerArray-20 ::= SEQUENCE (SIZE(20)) OF MyInteger(0 .. 255)
ArrayInterface-ArrayCommand2-Type ::= SEQUENCE
{
    arrayArgument1 MyIntegerArray-20(SIZE(20))
}
ArrayInterface-ArrayCommand3-Type ::= SEQUENCE
{
    arrayArgument1 MyIntegerArray-10(SIZE(10))
}
END

