-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by TASTE (kazoo/templates/glue/language_wrappers/ri_adb/function.tmplt)
package body Actuator_RI is

   procedure Reporting (Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Reporting
         (Dest_PID : asn1sccPID)
         with Import,
              Convention => C,
              Link_Name  => "actuator_RI_reporting_To_PID";
   begin
         C_Reporting (Dest_PID);
   end Reporting;

end Actuator_RI;
