all:
	mkdir -p code
	cd code && opengeode --toAda /home/taste/spacecreator/tests/manual/tmc/CdrDemo/work/modemanager/SDL/src/modemanager.pr "../system_structure.pr"
	asn1scc -fp AUTO -typePrefix asn1Scc -o code -equal -Ada dataview-uniq.asn code/modemanager_datamodel.asn
	cd code && gnat make modemanager
clean:
	rm -rf code