/* Header file for function Dummy
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void dummy_startup(void);

/* Provided interfaces */
void dummy_PI_Poll( void );

/* Required interfaces */
extern void dummy_RI_dummy( void );


#ifdef __cplusplus
}
#endif

