all:
	mkdir -p code
	cd code && opengeode --toAda /home/taste/taste-model-checker/validation_models/uart_protocol_dlc/work/rtdlcr/SDL/src/rtdlcr.pr 
	asn1scc -fp AUTO -typePrefix asn1Scc -o code -equal -Ada dataview-uniq.asn code/rtdlcr_datamodel.asn
	cd code && gnat make rtdlcr
clean:
	rm -rf code