all:
	mkdir -p code
	cd code && opengeode --toAda /home/taste/workspace/SpaceCreator/spacecreator/tests/integrationtests/applications/tmc/use-cases/resources/uart_protocol_dlc/work/modelchecking/properties/InputObserver/InputObserver.pr 
	asn1scc -fp AUTO -typePrefix asn1Scc -o code -equal -Ada observer.asn code/InputObserver_datamodel.asn
	cd code && gnat make InputObserver
clean:
	rm -rf code