/* Body file for function demo_Timer_Manager
 * Generated by TASTE on 2022-09-30 02:17:32
 */
#include "demo_timer_manager_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);




unsigned demo_timer_manager_initialized = 0;
void init_demo_timer_manager(void)
{
   if (0 == demo_timer_manager_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      demo_timer_manager_initialized = 1;
      // Call user code startup function
      extern void demo_timer_manager_startup(void);
      demo_timer_manager_startup();
      puts ("[TASTE] Initialization completed for function demo_Timer_Manager");
      demo_timer_manager_initialized = 2;
   }
}
void demo_timer_manager_RESET_rtdlcr_FrameTimer()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: demo_timer_manager,reset_rtdlcr_frametimer,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void demo_timer_manager_PI_RESET_rtdlcr_FrameTimer(void);
   demo_timer_manager_PI_RESET_rtdlcr_FrameTimer();
   // puts ("demo_timer_manager_reset_rtdlcr_frametimer called");
}




void demo_timer_manager_SET_rtdlcr_FrameTimer
      (const char *IN_val, size_t IN_val_len)

{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: demo_timer_manager,set_rtdlcr_frametimer,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void demo_timer_manager_PI_SET_rtdlcr_FrameTimer
      (const asn1SccT_UInt32 *);





   // Call user code
   demo_timer_manager_PI_SET_rtdlcr_FrameTimer ((asn1SccT_UInt32 *)IN_val);

}




void demo_timer_manager_Tick()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: demo_timer_manager,tick,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void demo_timer_manager_PI_Tick(void);
   demo_timer_manager_PI_Tick();
   // puts ("demo_timer_manager_tick called");
}

