/* Body file for function demo_Timer_Manager
 * Generated by TASTE on 2022-09-11 23:58:17
 */
#include "demo_timer_manager_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>




unsigned demo_timer_manager_initialized = 0;
void init_demo_timer_manager(void)
{
   if (0 == demo_timer_manager_initialized) {
      demo_timer_manager_initialized = 1;
      // Call user code startup function
      extern void demo_timer_manager_startup(void);
      demo_timer_manager_startup();
      puts ("[TASTE] Initialization completed for function demo_Timer_Manager");
      demo_timer_manager_initialized = 2;
   }
}
void demo_timer_manager_RESET_rtdlcr_FrameTimer()
{

   //  Directly call user code, no parameters to pass
   extern void demo_timer_manager_PI_RESET_rtdlcr_FrameTimer(void);
   demo_timer_manager_PI_RESET_rtdlcr_FrameTimer();
   // puts ("demo_timer_manager_reset_rtdlcr_frametimer called");
}




void demo_timer_manager_SET_rtdlcr_FrameTimer
      (const char *IN_val, size_t IN_val_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void demo_timer_manager_PI_SET_rtdlcr_FrameTimer
      (const asn1SccT_UInt32 *);





   // Call user code
   demo_timer_manager_PI_SET_rtdlcr_FrameTimer ((asn1SccT_UInt32 *)IN_val);

}




void demo_timer_manager_Tick()
{

   //  Directly call user code, no parameters to pass
   extern void demo_timer_manager_PI_Tick(void);
   demo_timer_manager_PI_Tick();
   // puts ("demo_timer_manager_tick called");
}

