/* ASN.1 System configuration file for function ErroredChannel
 * Generated by TASTE on 2022-09-30 01:33:13
 */
#define __NEED_UINT8_NATIVE




#define __NEED_UINT8_NATIVE
#define __NEED_UINT8_NATIVE
