/* Body file for function ErroredChannel
 * Generated by TASTE on 2022-09-11 23:58:17
 */
#include "erroredchannel_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>



extern void adainit(void);

unsigned erroredchannel_initialized = 0;
void init_erroredchannel(void)
{
   if (0 == erroredchannel_initialized) {
      erroredchannel_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      puts ("[TASTE] Initialization completed for function ErroredChannel");
      erroredchannel_initialized = 2;
   }
}
void erroredchannel_CorruptChar
      (const char *IN_p1, size_t IN_p1_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void erroredchannel_PI_CorruptChar
      (const asn1SccUINT8 *);





   // Call user code
   erroredchannel_PI_CorruptChar ((asn1SccUINT8 *)IN_p1);

}




void erroredchannel_DropChar()
{

   //  Directly call user code, no parameters to pass
   extern void erroredchannel_PI_DropChar(void);
   erroredchannel_PI_DropChar();
   // puts ("erroredchannel_dropchar called");
}




void erroredchannel_PHYTxChar
      (const char *IN_p1, size_t IN_p1_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void erroredchannel_PI_PHYTxChar
      (const asn1SccUINT8 *);





   // Call user code
   erroredchannel_PI_PHYTxChar ((asn1SccUINT8 *)IN_p1);

}

