/* Body file for function BCDLCT
 * Generated by TASTE on 2022-09-11 23:58:17
 */
#include "bcdlct_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>



extern void adainit(void);

unsigned bcdlct_initialized = 0;
void init_bcdlct(void)
{
   if (0 == bcdlct_initialized) {
      bcdlct_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      puts ("[TASTE] Initialization completed for function BCDLCT");
      bcdlct_initialized = 2;
   }
}
void bcdlct_DLCTxReset()
{

   //  Directly call user code, no parameters to pass
   extern void bcdlct_PI_DLCTxReset(void);
   bcdlct_PI_DLCTxReset();
   // puts ("bcdlct_dlctxreset called");
}




void bcdlct_DLCTxSDU
      (const char *IN_p1, size_t IN_p1_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void bcdlct_PI_DLCTxSDU
      (const asn1SccT_UART_DLC_SDU *);





   // Call user code
   bcdlct_PI_DLCTxSDU ((asn1SccT_UART_DLC_SDU *)IN_p1);

}




void bcdlct_PHYTxError()
{

   //  Directly call user code, no parameters to pass
   extern void bcdlct_PI_PHYTxError(void);
   bcdlct_PI_PHYTxError();
   // puts ("bcdlct_phytxerror called");
}

