-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
with Syncprocedures_Dataview; use Syncprocedures_Dataview;
with Taste_Basictypes;        use Taste_Basictypes;
with Simulation_Dataview; use Simulation_Dataview;
with Pinger;

package Pinger_PI is
   --  Interface to the simulation API
   procedure Startup (Global_State : in out asn1SccSystem_State);
   --  Execute only continuous signals (the simulator shall let the user
   --  send intermediate PIs in the queue since they have priority over
   --  continuous signals)
   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State);

   --  Provided interfaces
   procedure Pong
      (Global_State : in out asn1SccSystem_State;
      Pongarg : in out asn1SccMyinteger);
   
   
   
   procedure Tick (Global_State : in out asn1SccSystem_State);

end Pinger_PI;
