-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-07-19 15:52:40
with Simulator;            use Simulator;
with Simulation_Dataview;  use Simulation_Dataview;
with Ponger;
package body Pinger_RI is

   procedure Ping
      (Pingarg : in out asn1SccMyinteger) is
   begin
      --  The global state of the callee has been set, so we can make a direct call
      Ponger.Ping (pingArg);
   end Ping;

end Pinger_RI;
