-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2023-01-04 09:25:12
with Simulator;            use Simulator;
with Simulation_Dataview;  use Simulation_Dataview;
with System_Dataview;      use System_Dataview;
package body Function_1_RI is

   procedure Pi_1
      (P1 : in out asn1SccMyseqof) is
      --  Generate an event to the simulator for the output
      Event_Out_Function_2 : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_Function_2.Output_Event :=
        (Source => asn1sccFunction_1,
         Dest   => asn1sccFunction_2,
         Event  => (Kind => Function_1_PRESENT,
                    Function_1 =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Pi_1_PRESENT,
                     Pi_1 =>
                           (P1 => P1)))));
      Push_Event (Event_Out_Function_2);
   
   end Pi_1;

end Function_1_RI;
