-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- (Generated by TASTE/Kazoo - $TOOL_SRC/kazoo/templates/glue/language_wrappers/simu_pi_adb/function.tmplt)
package body Pinger_PI is

   procedure Update_States_For_Synchronous_Calls (Global_State : asn1SccSystem_State) is
   begin
      --  No synchronous RIs are connected to this function
      null;
   end Update_States_For_Synchronous_Calls;

   procedure Update_Global_State_After_Synchronous_Calls (Global_State : in out asn1SccSystem_State)  is
   begin
      --  No synchronous RIs are connected to this function
      null;
   end Update_Global_State_After_Synchronous_Calls;

   procedure Startup (Global_State : in out asn1SccSystem_State) is
   begin
      --  Initialize the global state after startup function has run
      Global_State.Pinger := Pinger.Ctxt;
   end Startup;

   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State) is
   begin
      Pinger.Ctxt := Global_State.Pinger;
      Pinger.Execute_Transition (Pinger.CS_Only);
      Global_State.Pinger := Pinger.Ctxt;
   end Continuous_Signals;

   --  Provided interfaces
   procedure Pong
      (Global_State : in out asn1SccSystem_State;
      Pongarg : in out asn1SccMyinteger) is
   begin
      -- Set the current context (provided by the simulation API)
      Pinger.Ctxt := Global_State.Pinger;
      --  If user code calls synchronous RIs, set their state too
      Update_States_For_Synchronous_Calls (Global_State);
      Pinger.Pong
         (Pongarg => Pongarg);
      -- Update the global state
      Global_State.Pinger := Pinger.Ctxt;
      --  If user code called synchronous RIs, populate their state
      Update_Global_State_After_Synchronous_Calls (Global_State);
   end Pong;
   
   
   procedure Tick (Global_State : in out asn1SccSystem_State) is
   begin
      -- Set the current context (provided by the simulation API)
      Pinger.Ctxt := Global_State.Pinger;
      --  If user code calls synchronous RIs, set their state too
      Update_States_For_Synchronous_Calls (Global_State);
      Pinger.Tick;
      -- Update the global state
      Global_State.Pinger := Pinger.Ctxt;
      --  If user code called synchronous RIs, populate their state
      Update_Global_State_After_Synchronous_Calls (Global_State);
   end Tick;

end Pinger_PI;
