-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-07-19 15:50:17
with Simulator;            use Simulator;
with Simulation_Dataview;  use Simulation_Dataview;
package body Pinger_RI is

   procedure Ping
      (Pingarg : in out asn1SccMyinteger) is
      --  Generate an event to the simulator for the output
      Event_Out_Ponger : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_Ponger.Output_Event :=
        (Source => asn1sccPinger,
         Dest   => asn1sccPonger,
         Event  => (Kind => Pinger_PRESENT,
                    Pinger =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Ping_PRESENT,
                     Ping =>
                           (Pingarg => Pingarg)))));
      Push_Event (Event_Out_Ponger);
   
   end Ping;

end Pinger_RI;
