-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-09-30 02:04:18
with Simulator;            use Simulator;
with Simulation_Dataview;  use Simulation_Dataview;
with System_Dataview;      use System_Dataview;
with demo_Timer_Manager;
with demo_Timer_Manager;
package body Rtdlcr_RI is

   procedure Dlcrxerror
      (P1 : in out asn1SccT_Uart_Dlc_Rxerrorcode) is
      --  Generate an event to the simulator for the output
      Event_Out_Rtapp : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_Rtapp.Output_Event :=
        (Source => asn1sccRtdlcr,
         Dest   => asn1sccRtapp,
         Event  => (Kind => Rtdlcr_PRESENT,
                    Rtdlcr =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Dlcrxerror_PRESENT,
                     Dlcrxerror =>
                           (P1 => P1)))));
      Push_Event (Event_Out_Rtapp);
   
   end Dlcrxerror;
   
   
   
   procedure Dlcrxsdu
      (P1 : in out asn1SccT_Uart_Dlc_Sdu) is
      --  Generate an event to the simulator for the output
      Event_Out_Rtapp : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_Rtapp.Output_Event :=
        (Source => asn1sccRtdlcr,
         Dest   => asn1sccRtapp,
         Event  => (Kind => Rtdlcr_PRESENT,
                    Rtdlcr =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Dlcrxsdu_PRESENT,
                     Dlcrxsdu =>
                           (P1 => P1)))));
      Push_Event (Event_Out_Rtapp);
   
   end Dlcrxsdu;
   
   
   
   procedure Reset_Frametimer is
   begin
      --  The global state of the callee has been set, so we can make a direct call
      Demo_Timer_Manager.Reset_Rtdlcr_Frametimer;
   end Reset_Frametimer;
   
   
   
   procedure Set_Frametimer
      (Val : in out asn1SccT_Uint32) is
   begin
      --  The global state of the callee has been set, so we can make a direct call
      Demo_Timer_Manager.Set_Rtdlcr_Frametimer (Val);
   end Set_Frametimer;

end Rtdlcr_RI;
